### ISSUE TITLE
Inside proxy

### ISSUE THREAD

**Issue by alex-moreno** [perftools/xhgui#107]
this will not work inside a proxy environment (in fact it doesn't):

https://github.com/perftools/xhgui/blob/master/install.php#L56

**Comment by vad1m** [comment]
I think you can add to global config variable like USE_PROXY = ''.
Then using example from php.net (just as an idea, not final code):

config:
``
USE_PROXY = 'tcp://127.0.0.1:8080'
``

app:
``
// Define a context for HTTP.
if ($USE_PROXY) {
$aContext = array(
    'http' => array(
        'proxy' => $USE_PROXY, // This needs to be the server and the port of the NTLM Authentication Proxy Server.
        'request_fulluri' => True,
        ),
    );
$cxContext = stream_context_create($aContext);
// Now all file stream functions can use this context.
$sFile = file_get_contents("https://getcomposer.org/installer", False, $cxContext);
}
else {
file_get_contents('https://getcomposer.org/installer');
}
``

**Comment by vad1m** [comment]
as an another option, if you don't want implement all possible proxy cases, you can just add next feature:
in case of download failure just show message like
```
download failed, possible reasons:
- you're behind proxy
- composer servers is not available at the moment
- something wrong with network configuration.
please try download it manually.
```

**Comment by markstory** [comment]
@vad1m I like the error message approach. I've done that in d6442c1.
