### ISSUE TITLE
How to differentiated between domains?

### ISSUE THREAD

**Issue by thebeline** [perftools/xhgui#125]
I am running this on multiple domains, how do I differentiate between them?

**Comment by Mte90** [comment]
Ping for this, there is a way to add the domain instead of only urls (without domains)?

**Comment by Mte90** [comment]
It is very strange because we have `/a-glus-of-the-url` but no `demo.test/a-slug-of-the-url`.
Where is required to change that? I can try to do something.

**Comment by markstory** [comment]
@Mte90 when data is saved by the collector https://github.com/perftools/xhgui-collector/blob/efbc19d2a0aa7905b1fc4a38baedc4a9f716a56e/external/header.php#L160 we would need to track the host separately. Having that would allow the ui to create host specific displays or allow searching by host.

**Comment by Mte90** [comment]
As I can see store the `$_SERVER` but this doesn't already include the domain on `$_SERVER['SERVER_NAME']`?

**Comment by markstory** [comment]
Good point. The server data also contains the host.

**Comment by Mte90** [comment]
So we need to change only the UI to show that data to start only on the list and later on the rest?

**Comment by Mte90** [comment]
any updates for this? I am integrating xhgui on VVV and there is the support of multiple domains.
I don't think that I have time to work on that right now.

**Comment by markstory** [comment]
> any updates for this?

Not really. I haven't had much time to dedicate to this project recently.

**Comment by glensc** [comment]
Showing hostname in listing was added in #243 (0.10.0)

For filtering, there's still open issue: https://github.com/perftools/xhgui/issues/63
