### ISSUE TITLE
Remove dependency with ext-xhprof in composer.json

### ISSUE THREAD

**Issue by olivier34000** [perftools/xhgui#127]
In the file composer.json there is a dependency with "ext-xhprof": "*". However the extension ext-uprofilter is valid too. I suggest to remove the dependency

**Comment by preinheimer** [comment]
We've talked about this a bit. The ideal situation would be an "OR" option inside composer.json, (ext-xhprof OR ext-uprofiler) but that's not an option yet. We would also like to call out to people during the installation process that *something* is required.

What about composer.json and composer.json.uprofiler or some other chicanery?

**Comment by akrabat** [comment]
I've just been bitten by this.

Setting it as a "[suggestion](https://getcomposer.org/doc/04-schema.md#suggest)" would enable you to call out the requirement for one of them.

**Comment by markstory** [comment]
I think #135 fixes this.
