### ISSUE TITLE
Read timed out after reading 0 bytes, waited for 30.000000 seconds

### ISSUE THREAD

**Issue by khosro** [perftools/xhgui#131]
I get the exception "Read timed out after reading 0 bytes, waited for 30.000000 seconds" in the following URLS:
1./url/view
2./run/compare
I can view those pages by setting "MongoCursor::$timeout = -1",but it takes more than 2 minutes to render those pages.
Other pages rendered in normal waiting time.

**Comment by markstory** [comment]
Yep mongo is sometimes terrible. Make sure you add the index as per the readme, that often helps.

**Comment by khosro** [comment]
Yes ,I followed README step by step and also added index,but as i said i got this exception.
I imported 1G data to MongoDB.

**Comment by markstory** [comment]
You might have an issue with mongos configuration. I am still pretty green with mongo and don't really know what the issue could be.

**Comment by khosro** [comment]
My MongoDB configuration is default.I do not change it.

**Comment by voukka** [comment]
I want to confirm that it also happens for our case. All indexes are in place. There are only 30k results in db, totalling xhprof	53GB of data. Yes, our profiles are somewhat big though. DB is on SSD but it is unable to catch up within 30 secs

**Comment by dcroonen** [comment]
We are having the same issue on a dataset of almost 60GB where we sharded the MongoDB  over three servers. @khosro in which file did you set the MongoCursor::$timeout = -1 ?

**Comment by khosro** [comment]
@dcroonen ,
In class `Xhgui_Profiles ` ,i changed `getPercentileForUrl` method :
     
       public function getPercentileForUrl($percentile, $url, $search = array())
    {
        MongoCursor::$timeout = -1;//Khosro
       
And also in the mentioned class,i changed method `paginate($options)` as follows :
     
        public function paginate($options)
    {
        $opts = $this->_mapper->convert($options);

        /*
         * Khosro comment
         * $totalRows = $this->_collection->find(
            $opts['conditions'],
            array('_id' => 1))->count();*/
        //Khosro
        $cursor1 = $this->_collection->find(
            $opts['conditions'],
            array('_id' => 1));
        $cursor1->timeout(-1);
        $totalRows= $cursor1->count();
        //Khosro

But it is only temporary fix and only a test whether page renders and does not apply in real world scenario.
