### ISSUE TITLE
Error when clicking on URL links

### ISSUE THREAD

**Issue by Benjen** [perftools/xhgui#134]
I have installed xhgui but encounter an error anytime I click on a link in the URL column of a page. I have attached a screen shots showing both the link and the corresponding error.  Any suggestions on how this can be resolved?

![xhgui-run-list](https://cloud.githubusercontent.com/assets/1292616/6545378/95cbd350-c5d8-11e4-8469-480371ab73a0.png)

![xhgui](https://cloud.githubusercontent.com/assets/1292616/6545374/320f1dfe-c5d8-11e4-905c-8688215d4fdd.png)

**Comment by markstory** [comment]
You might have an old version of the mongo driver extension.

**Comment by leomylonas** [comment]
Hey Mark, has there been any update to this? I'm having the same issue.

**Comment by markstory** [comment]
@leomylonas There has not. I've not had much time recently to dedicate to this. If you have the time I'd really appreciate a hand in getting it fixed.

**Comment by leomylonas** [comment]
Normally I would, but I have absolutely no idea of the underlying technologies here, so I fear I wouldn't be much help. I'm just trying to work out why my web app is running slow! :-P

**Comment by belanur** [comment]
@leomylonas It is likely that you are using a version of MongoDB that does not support `db.collection.aggregate()`.I ran into the same issue with MongoDB 2.0.6 on Debian 7. 

Afaik `db.collection.aggregate()` has been introduced in 2.2, so upgrading your MongoDB version might solve the issue.
