### ISSUE TITLE
Delete a run

### ISSUE THREAD

**Issue by Moosh-be** [perftools/xhgui#136]
Sometime it's happen to launch a run in a bad context, the result can "broke"  the graph.

It would be cool to be able to ignore/delete this run entry.

**Comment by Moosh-be** [comment]
if you approve, but don't have time, I can try to fork, write and pull request a solution

**Comment by markstory** [comment]
A pull request for this would be great :smile:

**Comment by jamesrward** [comment]
👍

**Comment by Krinkle** [comment]
Is this resolved by https://github.com/perftools/xhgui/pull/238, or is there more to be done?
