### ISSUE TITLE
"127.0.0.1:27017: no such cmd"

### ISSUE THREAD

**Issue by archibaldhaddock** [perftools/xhgui#144]
Hello everybody,

I've just cloned xhgui and installed 
mongo --version
MongoDB shell version: 1.4.4
I browsed  the site I want to profile, I get a correct list of urls on xhgui main page but when I click on one of them to get details I have this message
"Aw shoot, Xhgui hit an error
127.0.0.1:27017: no such cmd"
What is sure is that the connection to mongo seems ok.
Here is what I get with a few requests on my site followed by a xhgui "get details" on a particular url
tail -f /var/log/mongodb/mongodb.log 
Thu Jun 25 18:45:21 run command admin.$cmd { isMaster: 1 }
Thu Jun 25 18:45:21 query admin.$cmd ntoreturn:1 command  reslen:109 0ms
Thu Jun 25 18:45:21 run command admin.$cmd { buildInfo: 1 }
Thu Jun 25 18:45:21 query admin.$cmd ntoreturn:1 command  reslen:110 0ms
Thu Jun 25 18:45:21 run command admin.$cmd { ping: 1 }
Thu Jun 25 18:45:21 query admin.$cmd ntoreturn:1 command  reslen:105 0ms
Thu Jun 25 18:45:21 query xhprof.results ntoreturn:1 reslen:2153 nreturned:1 0ms
Thu Jun 25 18:45:21 run command xhprof.$cmd { count: "results", query: { meta.simple_url: "/wp_nxtweb/e-commercant/" } }
Thu Jun 25 18:45:21 query xhprof.$cmd ntoreturn:1 command  reslen:64 0ms
Thu Jun 25 18:45:21 query xhprof.results ntoreturn:25 reslen:2349855 nreturned:4 0ms
Thu Jun 25 18:45:21 run command xhprof.$cmd { aggregate: "results", pipeline: { 0: { $match: { meta.simple_url: "/wp_nxtweb/e-commercant/" } }, 1: { $project: { date: "$meta.request_date", profile.main(): 1 } }, 2: { $group: { _id: "$date", row_count: { $sum: 1 }, wall_times: { $push: "$profile.main().wt" }, cpu_times: { $push: "$profile.main().cpu" }, mu_times: { $push: "$profile.main().mu" }, pmu_times: { $push: "$profile.main().pmu" } } }, 3: { $project: { date: "$date", row_count: "$row_count", raw_index: { $multiply: { 0: "$row_count", 1: 0.9 } }, wall_times: "$wall_times", cpu_times: "$cpu_times", mu_times: "$mu_times", pmu_times: "$pmu_times" } }, 4: { $sort: { _id: 1 } } } }
Thu Jun 25 18:45:21 query xhprof.$cmd ntoreturn:1 command  reslen:787 0ms
Thu Jun 25 18:45:42 end connection 127.0.0.1:34782

I'm wondering 
1) if the last commit git version is OK with my mongo db version
2) if mysql is still usable with xhgui? It seems that the code does not even "grep -i mysql" ?
Thanks for your answer(s) !

**Comment by markstory** [comment]
This codebase does not support mysql at all. I am not to sure about compatibility issues with different versions of mongo though.

**Comment by gwenael** [comment]
Ok, thanks for your answer.
Since "no such cmd" clearly comes from mongo (cli or db) + I don't know how to fix it, I'll get back to an older version that can use mysql.

**Comment by gwenael** [comment]
Finally, I've installed mongodb 3.0.4 and everything works fine !
thanks !
