### ISSUE TITLE
Can't disable XHPROF_FLAGS_CPU flag

### ISSUE THREAD

**Issue by boedy** [perftools/xhgui#146]
When I leave out the `XHPROF_FLAGS_CPU` in `xhprof_enable(XHPROF_FLAGS_CPU | XHPROF_FLAGS_MEMORY);` I get the following error when I view a trace.

![image](https://cloud.githubusercontent.com/assets/2030968/9194820/596e0002-401e-11e5-8e23-15907e4be5a0.png)

**Comment by markstory** [comment]
Yes, xhgui assumes you have cpu profiling enabled throughout the code unfortunately.

**Comment by glensc** [comment]
Here's a snapshot of profiling data:
- no flags: https://github.com/perftools/php-profiler/blob/0.14.0/tests/Resources/tideways_xhprof.json
- cpu flags: https://github.com/perftools/php-profiler/blob/0.14.0/tests/Resources/tideways_xhprof_cpu.json
- cpu & mem flags: https://github.com/perftools/php-profiler/blob/0.14.0/tests/Resources/tideways_xhprof_cpu_memory.json

so, in case you wonder what the data is, with no flags it's not completely empty, contains "ct" and "wt" keys (clock time, wallclock time?)

**Comment by glensc** [comment]
@ngyuki: https://github.com/perftools/xhgui/pull/362
