### ISSUE TITLE
xhgui keeps getting profiled

### ISSUE THREAD

**Issue by jamesrward** [perftools/xhgui#148]
I'm running nginx php-fpm 5.6 and xhgui all installed via homebrew.  For the domain I want to profile I have include the nginx config for php files
```
location ~ \.php$ {
    try_files      $uri = 404;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PHP_VALUE "auto_prepend_file=/usr/local/opt/php56-xhgui/external/header.php";
    include        fastcgi_params;
   }
```
For xhgui I have the following:
```    
location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass    127.0.0.1:9000;
        fastcgi_index   index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
```
For some reason after I load a the domain I want to profile xhgui starts profiling itself.  I have to periodically remove xhgui records with:
```db.results.remove({"meta.SERVER.HTTP_HOST" :"xhgui.ld"})```
But even that seems to still let some through.

Is it possible that the fastcgi_params being included in the xhgui config are pulling in the param I set for another domain?

**Comment by markstory** [comment]
Its very possible that fastcgi worker processes are shared between the two virtualhosts. This is very likely to happen because you're modifying the PHP configuration in fastcgi.

**Comment by jamesrward** [comment]
That's what I figured.  Any suggestions for a work-around or should I just stick with including the header.php file in the projects I want to profile?

**Comment by markstory** [comment]
If you're using php-fpm you might want to stick with requiring the header.php file.
