### ISSUE TITLE
Can you please add develop branch

### ISSUE THREAD

**Issue by woss** [perftools/xhgui#150]
Hi,

can you please add DEVELOP branch so i can make pull request. I use GitFlow for all my projects and i would recommend that you utilise that coz it makes easier for contributors to make pull request.

Made few changes to view twig template to see the VERB of each method, much easier to distinguish what i would like to see.

Thanks

**Comment by dennisdegreef** [comment]
You can also make a pull request to master :)

**Comment by woss** [comment]
ok :) thanks will do

**Comment by markstory** [comment]
I really dislike gitflow as the two long lived branches make almost no sense for a project like this.  Closing as your pull request has been merged :smile:.

**Comment by woss** [comment]
@markstory that is true. thanks for merging pull request :smiley:
