### ISSUE TITLE
Performance index calculation

### ISSUE THREAD

**Issue by dkarlovi** [perftools/xhgui#154]
My company is a webdev studio and we're doing quite a few different projects. I like the idea of using this tool remotely (ie. I've developed a plugin for our framework which dumps the profile in a file on disk and a cron job picks it up and uploads it to our one hosted xhgui instance). This, combined with other tools we use, would enable us to have a constant "finger on the performance pulse" of our apps, but to really be able to do this, we would need to have a at-a-glance picture of the current state.

What I'm thinking is having an "performance index" which would, roughly said, be a number which represents what the overall performance of the app is. If it's (let's say) 7, that's better than yesterday's 11 so you can easily gauge the performance fluctuations. 

I'm not currently clear on how it would be calculated, obviously, we would take some sort of aggregate of wall time in a certain time period and divide by number of samples, ideas very welcome. This should enable us to be able to draw a performance graph for a certain project and figure out are we better or worse after our latest deploy than before it, performance-wise. Idea is to add a overview graph on the dashboard like, say, Sentry dashboard has:

![Sentry dashboard screenshot](https://assets.getapp.com/screenshot/r/91580-2051716025.png) 

If any of this sounds interesting, please comment. I'll probably do this in my fork (along with the support for multiple apps in one instance) so even if the feature is not widely wanted, I'd like the feedback.

**Comment by markstory** [comment]
I think it sounds neat. Having the performance index displayed on the run list would be quite handy.

**Comment by dkarlovi** [comment]
@markstory thanks for your comment. Do you have a rough idea how it might work?

I'm thinking out loud: we'll have to sample in discrete time intervals (which is a fancy way to say "by minute", "by hour", etc). This gives us an X axis, time.

Y axis: for each interval we can collect all the samples which fit in that interval and average their wall time (probably need to use median, to ease the curve). This *might* give us a rough idea how the app behaved in that period.

I'd say we should go from there and tweak.

**Comment by markstory** [comment]
>  Do you have a rough idea how it might work?

Nope :smile: Something using percentiles might work out ok.

**Comment by dkarlovi** [comment]
OK, so let's do *something* and see how it performs, we'll be smarter from there. :)

**Comment by dkarlovi** [comment]
Also, before I forget: I think we should also store the current profiling rate with each profile. This would roughly translate as "This profile represents X requests" and might possibly be used in the calculation.
