### ISSUE TITLE
Undefined offset errors in Profiles.php::getPercentileForUrl()

### ISSUE THREAD

**Issue by BHSPitMonkey** [perftools/xhgui#155]
When I try to visit `/url/view` pages, I am met with the error page:

```
Aw shoot, Xhgui hit an error

Undefined offset: 4
```

Here is the stack trace displayed:

```
#0 /var/www/xhgui/src/Xhgui/Profiles.php(189): Slim\Slim::handleErrors(8, 'Undefined offse...', '/var/www/xhgui/...', 189, Array)
#1 /var/www/xhgui/src/Xhgui/Controller/Run.php(129): Xhgui_Profiles->getPercentileForUrl(90, '/home/index', Array)
#2 /var/www/xhgui/src/routes.php(35): Xhgui_Controller_Run->url()
#3 [internal function]: {closure}()
#4 /var/www/xhgui/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#5 /var/www/xhgui/vendor/slim/slim/Slim/Slim.php(1302): Slim\Route->dispatch()
#6 /var/www/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /var/www/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /var/www/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(117): Slim\Middleware\MethodOverride->call()
#9 /var/www/xhgui/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie->call()
#10 /var/www/xhgui/vendor/slim/slim/Slim/Slim.php(1251): Xhgui_Middleware_Render->call()
#11 /var/www/xhgui/webroot/index.php(10): Slim\Slim->run()
#12 {main}
```

The problem seems to be in how an array offset gets calculated in PHP.
See this snippet from src/Xhgui/Profiles.php:

``` php
$keys = array(
    'wall_times' => 'wt',
    'cpu_times' => 'cpu',
    'mu_times' => 'mu',
    'pmu_times' => 'pmu'
);
foreach ($results['result'] as &$result) {
    $result['date'] = ($result['_id'] instanceof MongoDate) ? date('Y-m-d H:i:s', $result['_id']->sec) : $result['_id'];
    unset($result['_id']);
    $index = max(round($result['raw_index']) - 1, 0);
    foreach ($keys as $key => $out) {
        sort($result[$key]);
        $result[$out] = $result[$key][$index];
        unset($result[$key]);
    }
}
```

The logic at `$index = max(round($result['raw_index']) - 1, 0);` looks clunky and seems to produce out-of-bounds indexes for me. For instance, here is the contents of `$result` for one of my runs:

```
    ["row_count"]=>
    int(6)
    ["wall_times"]=>
    array(3) {
      [0]=>
      int(1711)
      [1]=>
      int(1824)
      [2]=>
      int(5840)
    }
    ["cpu_times"]=>
    array(3) {
      [0]=>
      int(0)
      [1]=>
      int(4000)
      [2]=>
      int(0)
    }
    ["mu_times"]=>
    array(3) {
      [0]=>
      int(84728)
      [1]=>
      int(110872)
      [2]=>
      int(84664)
    }
    ["pmu_times"]=>
    array(3) {
      [0]=>
      int(42104)
      [1]=>
      int(63008)
      [2]=>
      int(40552)
    }
    ["raw_index"]=>
    float(5.4)
    ["date"]=>
    string(10) "2015-09-28"
```

Because `raw_index` is 5.4, this produces a `$index` of 4 which does not exist in the result arrays.

**Comment by markstory** [comment]
It would seem that one or more metrics have been disabled. Is that the case?

**Comment by BHSPitMonkey** [comment]
Could you clarify? I'm not sure how to disable/enable metrics, or how to verify which ones are enabled currently. In the `external/header.php` I'm including, it appears I'm using the `XHPROF_FLAGS_CPU` and `XHPROF_FLAGS_MEMORY` xhprof flags if that's what you mean.

**Comment by markstory** [comment]
The various flag options passed to `xhprof_enable` toggle different metrics not being collected.

**Comment by BHSPitMonkey** [comment]
I haven't deliberately disabled any of the metrics, and I'm still unsure how I would. Regardless, though, is this PHP fatal error an intended result of disabling a metric or is it a bug?

**Comment by markstory** [comment]
> Regardless, though, is this PHP fatal error an intended result of disabling a metric or is it a bug?

I would consider it a bug either way, I was just trying to understand why the metrics are missing.

**Comment by magnetik** [comment]
Got the same error with almost non modified config, and the tideways extension activated.

**Comment by douglasjam** [comment]
any news?

**Comment by douglasjam** [comment]
At least for me, this only happen when i click in the URL and not in the date.

**Comment by Krinkle** [comment]
Might be related to https://github.com/perftools/xhgui/issues/240

**Comment by glensc** [comment]
I think this is resolved with https://github.com/perftools/xhgui/pull/362

Please create new issue, if that's not the case.
