### ISSUE TITLE
Pecl mongo driver is superseded

### ISSUE THREAD

**Issue by jrbarnard** [perftools/xhgui#166]
The current xhgui release requires the old mongo php driver which has been superseded by: https://github.com/mongodb/mongo-php-driver

Are there plans to update support so it works with the newer driver?

**Comment by markstory** [comment]
No plans at the present, but if someone finds the time to contribute a solution I'd be happy to merge it.

**Comment by sylus** [comment]
This tripped me up as well when using PHP 7 which doesn't use the legacy driver.

I think we might need to leverage https://github.com/mongodb/mongo-php-library ?

**Comment by jimb50** [comment]
Cheers, just looking at Derick Rethans posts about the history of the old and new drivers and it looks as if he's writing a [migration guide to be released soon](https://derickrethans.nl/new-drivers-part2.html), I'll have a look at the core differences between the new driver + library over the old driver in the meantime, otherwise I may just wait for that write up to happen.

**Comment by martindanielsson** [comment]
I got it working locally but I haven't looked at the tests yet which are failing. I think it's got something to do with the fixtures but haven't worked with MongoDB before so I am not sure what to fix..

https://github.com/martindanielsson/xhgui/tree/support-new-mongodb-driver

**Comment by markstory** [comment]
@martindanielsson Looking good. I would start by making sure the fixtures are inserting correctly and into the write database.

**Comment by 2tvenom** [comment]
@martindanielsson got error in view http://take.ms/qQYDo
can you check? thank you

**Comment by denji** [comment]
* [pecl-mongodb](https://pecl.php.net/package/mongodb) (2.4 - 3.2)
* [pecl-mongo](https://pecl.php.net/package/mongo) (2.4 - 2.6/3.0)

| PHP Driver               | MongoDB 2.4 | MongoDB 2.6 | MongoDB 3.0 | MongoDB 3.2 |
|--------------------------|-------------|-------------|-------------|-------------|
| PHPLIB 1.0 + mongodb-1.1 | ✓           | ✓           | ✓           | ✓           |
| mongodb-1.1              | ✓           | ✓           | ✓           | ✓           |
| mongodb-1.0              | ✓           | ✓           | ✓           |             |
| mongo-1.6                | ✓           | ✓           | ✓           |             |
| mongo-1.5                | ✓           | ✓           |             |             |

**Comment by markstory** [comment]
@denji Ok. I don't really know what to do with that information. Xhgui is currently compatible with both the `pecl-mongo` and `pecl-mongodb` extensions. Perhaps this issue can be closed now?

**Comment by thias** [comment]
I have only the newer PECL mongodb 1.1.8 extension, and things are mostly working, so it seems like this report might no longer be relevant.

Then again, issue #188 which I am seeing too might be related.

**Comment by neclimdul** [comment]
header.php uses MongoDate which doesn't exist in pecl-mongodb so not 100% compatible yet.

**Comment by tm1000** [comment]
According to #220 you have to use mongodb driver (the newer one) as the older mongo doesnt work at all (composer refuses to install). Thus this should be closed. See #220 for more information

**Comment by jrbarnard** [comment]
@tm1000 Thanks, will close
