### ISSUE TITLE
htaccess and "Example configuration for Apache 2.4"

### ISSUE THREAD

**Issue by jcabillot** [perftools/xhgui#167]
Hi,

In your README.MD you give an exemple for the configuration of a VirtualHost in Apache :
```
<Directory /var/www/xhgui/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```
Because you only use rewrite instruction in your webroot/.htaccess, you only need to override FileInfo (https://httpd.apache.org/docs/current/fr/mod/mod_rewrite.html#rewriteengine).

So a better configuration exemple should be :
```
<Directory /var/www/xhgui/>
    Options Indexes FollowSymLinks
    AllowOverride FileInfo
    Require all granted
</Directory>
```
AllowOverride All permit to override some PHP configuration like open_basedir and other security stuff...

**Comment by markstory** [comment]
Would you be willing to open a pull request to update the README?
