### ISSUE TITLE
Where to put the *.xhprof files?

### ISSUE THREAD

**Issue by automatix** [perftools/xhgui#182]
Where should the profiling result files be stored, in order XHGui can see and process them? Ist is configurable?

**Comment by markstory** [comment]
XHGui cannot read the .xhprof files natively. You have to import the files into mongodb before you can look at the results. The filesaver mode is offered so that you don't need to run mongo in production should you want to use xhgui on production systems.

**Comment by maltfield** [comment]
@markstory can you please provide more information on how one can actually import the files into mongodb?

My fresh install just says

```
Looks like you haven't done any profiling

To get started with XHGUI you'll need to collect some profiling data.

See Profiling a Web Request or CLI script section of the readme file
```

That links-me to here:

 * https://github.com/perftools/xhgui#profiling-a-web-request-or-cli-script

And the above documentation says

```
php external/import.php -f /path/to/jsonlinesfile.jsonl
```

But I don't have a `.jsonl` file (what even *is* a `.jsonl` file?). I have (big surprise) a `.xhprof` file.

fwiw, I'm using docker on debian 11 as I just want to quickly view my first xhprof file locally.

```
sudo su -
sudo apt-get install docker.io docker-compose
git clone https://github.com/perftools/xhgui.git
cd xhgui
docker-compose up -d
```

After the above commands, I can load XHGui here http://localhost:8142

But I get a 404 when trying to load the `import.php` script

 * http://localhost:8142/external/import.php

How the heck do we import the `.xhprof` files into the MongoDB?

**Comment by glensc** [comment]
`php external/import.php` is a command line script, as indicated with an example:

```
php external/import.php -f /path/to/jsonlinesfile.jsonl
```

`.jsonl` files come from a collector, as indicated staring of that section:
> The recommended way to profile an application is to use [perftools/php-profiler](https://github.com/perftools/php-profiler) ([ on 25 Feb](https://github.com/perftools/php-profiler/tree/f860cb59e39ca67c3db37f680e8cd3b460db68fb)) package.

and you yourself have not disclosed information on how you obtained `.xhprof` file. no steps to reproduce. what is `.xhprof` file?

**Comment by maltfield** [comment]
> you yourself have not disclosed information on how you obtained .xhprof file. no steps to reproduce. what is .xhprof file?

Sorry, my understanding was that `.xhprof` was a standard filetype. It was originally [developed by Facebook and open-sourced in 2009](https://code-dev.fb.com/2009/04/02/production-engineering/xhproflive-continuous-function-level-performance-stats-from-production/).

The official documentation states that the `xhprof_disable()` command returns an array. When this array is written to a file (eg with `file_put_contents()`, the result is an `.xhprof` file.

Personally, I use the `tideways-xhprof` fork to generate `.xhprof` files. According to their [github repo's](https://github.com/tideways/php-xhprof-extension) README:

> This PHP extension is a complete, modernized open-source rewrite of the original XHProf extension, with a new core datastructure and specifically optimized for PHP 7. The result is an **XHProf data-format** compatible extension

You can also generate `.xhprof` files using the `XHProfRuns_Default` object and `save_run()` method from the [phacility fork of xhprof](https://github.com/phacility/xhprof).

```
include_once( '/var/www/xhprof/xhprof_lib/utils/xhprof_runs.php' );

$results = tideways_xhprof_disable();
$XHProfRuns = new XHProfRuns_Default( '/path/to/my/xhprof/dir' );
$XHProfRuns->save_run( $results, "myapp" );
```

My understanding was that XHGui was a data visualization tool for viewing the contents of these `.xhprof` files. Is that not correct?

Do you need me to provide an example file in `.xhprof` format?

**Comment by glensc** [comment]
xhgui needs it's own format, which is result of `tideways_xhprof_disable()` (or similar) plus additional metadata encoded as json:
- https://github.com/perftools/php-profiler/blob/1.0.2/src/ProfilingData.php#L21-L71

also, you can not write `Array` to a file, you need to serialize it somehow. This project uses JSON format.
