### ISSUE TITLE
Undefined index: mu

### ISSUE THREAD

**Issue by heylarson** [perftools/xhgui#189]
When accessing the following URI: ```GET /run/view?id=57fd51b92b02db123c0c0712```, I'm receiving the following error ```Undefined index: mu```, with the exception:

```
#0 /var/www/xhgui/src/Xhgui/Profile.php(361): Slim\Slim::handleErrors(8, 'Undefined index...', '/var/www/xhgui/...', 361, Array)
#1 /var/www/xhgui/src/Xhgui/Controller/Run.php(69): Xhgui_Profile->calculateSelf()
#2 /var/www/xhgui/src/routes.php(30): Xhgui_Controller_Run->view()
```

I'm running PHP v7.0.11, with the following mongodb extension:

```
mongodb

mongodb support => enabled
mongodb version => 1.1.8
mongodb stability => stable
libmongoc version => 1.3.5
libbson version => 1.3.5

Directive => Local Value => Master Value
mongodb.debug => no value => no value
```

With the following xhprof extension:
```
xhprof

xhprof => 0.9.2
CPU num => 2
```

And the latest commit of xhgui is ```7e35a4f2a2e21cc66a5a4e5a6b3840dc12ed03ad```

My mongod service (v3.2.10) is running, the cache directory is 777, and the ```config/config.php``` has the correct mongodb connection info.

Any suggestions?

**Comment by markstory** [comment]
The `mu` key tracks memory usage, I'm not sure why xhprof is not tracking those metrics for you though.

**Comment by heylarson** [comment]
I thinks [this issue](https://github.com/phacility/xhprof/issues/82#issuecomment-238888790) might be the underlying problem.

**Comment by markstory** [comment]
Have you considered trying the [tideways extension](https://github.com/tideways/php-profiler-extension) or [uprofiler](https://github.com/FriendsOfPHP/uprofiler) ? They might provide better compatibility with PHP7.

**Comment by heylarson** [comment]
Great suggestion! I'll try them out today and report back.

**Comment by heylarson** [comment]
tideways extension has worked great so far with php7

**Comment by joebordes** [comment]
Hi
I just ran into this issue. I am using the tideways extension but it is not collecting any mu nor cpu information.
Did you configure it somehow to activate that?

thanks

**Comment by joebordes** [comment]
I got it working by calling tideways with the correcet parameters:

```
tideways_enable(TIDEWAYS_FLAGS_NO_SPANS + TIDEWAYS_FLAGS_CPU + TIDEWAYS_FLAGS_MEMORY);
```

HTH
