### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by poolerMF** [perftools/xhgui#191]
hello ... 

when someone use php7, xhprof must be installed like this:

```
git clone https://github.com/longxinH/xhprof
cd xhprof/extension
phpize
./configure --with-php-config=/usr/bin/php-config7.0
sudo make && sudo make install
```

I spent some hours on this ...
repository https://github.com/RustJason/xhprof or https://github.com/phacility/xhprof do not work for php7

**Comment by markstory** [comment]
Could you send a pull request with the changes that should be made to the README?

**Comment by poolerMF** [comment]
I'm just informing you, that this is important information I think
you can update it if you want
I'm sorry, I will not make pull request

**Comment by markstory** [comment]
Thanks..
