### ISSUE TITLE
Update Slim to 2.4.0 or higher

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui#192]
ext-mcrypt was removed as a dependency in 2.4.0. ext-mcrypt wasn't a hard dependency in the first place, but was incorrectly present in composer.json before the 2.4.0 release in 2013.

Also:
> From **[ext/mcrypt](http://php.net/manual/en/migration71.deprecated.php)** at php.net
> The mcrypt extension has been abandonware for nearly a decade now, and was also fairly complex to use. It has therefore been deprecated [..] will be removed from the core in PHP 7.2.

I'm having issues installing xhgui because of ext-mcrypt not being present in my build environment.

**Comment by markstory** [comment]
Any chance you'd be interested in helping upgrade to slim 2.4?

**Comment by Krinkle** [comment]
@markstory Created a pull created for 2.4.x and one for 2.6.x. Seems there haven't been any breaking changes. I'll leave to you to choose which you prefer at this time.
