### ISSUE TITLE
XHGui on PHP7.0 with TideWays extension (instead of Xhprof) - MongoDB fails on macOS brew

### ISSUE THREAD

**Issue by mobilizer** [perftools/xhgui#198]
I do not get php70-tideways working with Xhgui on OS X with brew php70.  (same for php56)
I get the following error: `FastCGI: incomplete headers (0 bytes) received from server`

XHGui and Tideways is added via 
   
     php_value[auto_prepend_file]  = Users/..../xhprof/xhgui/external/header.php

I think I am missing some configuration.

ext-tideways.ini:  

    [tideways]
    extension="/usr/local/Cellar/php70-tideways/v4.0.7/tideways.so"
    tideways.connection=unix:///usr/local/var/run/tidewaysd.sock
    tideways.load_library=0

php -i:

     tideways => 4.0.7
     Connection (tideways.connection) => unix:///usr/local/var/run/tidewaysd.sock
     UDP Connection (tideways.udp_connection) => 127.0.0.1:8135
     Default API Key (tideways.api_key) =>
     Default Sample-Rate (tideways.sample_rate) => 30
     Framework Detection (tideways.framework) =>
     Automatically Start (tideways.auto_start) => Yes
     Tideways Collect Mode (tideways.collect) => tracing
     Tideways Monitoring Mode (tideways.monitor) => basic
     Allowed Distributed Tracing Hosts (tideways.distributed_tracing_hosts) => 127.0.0.1
     Load PHP Library (tideways.auto_prepend_library) => Yes
     Tideways.php found => Yes

Is the tideways-daemon needed for using tideways as replacement for Xhprof?
Deamon ist just for connection to the Tideways (payed) service!? Correct?

Is anybody running XhGui with TideWays extension instead of XhProf?

**Comment by markstory** [comment]
Have you checked you webserver error logs? From my understanding if you are connecting to the tideways daemon it will need to be running.

**Comment by mobilizer** [comment]
It seams to be a problem with php70-mongodb. 
Saving to file with `'save.handler' => 'file'` works.

It fails silently in MongoDB\Client constructor:

    $this->manager = new Manager($uri, $uriOptions, $driverOptions); 

I also did a clean install of XhGui:

 ```
  - Installing slim/slim (2.6.3): Loading from cache
  - Installing slim/views (0.1.0): Loading from cache
  - Installing pimple/pimple (v1.0.2): Loading from cache
  - Installing symfony/yaml (v2.8.18): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (1.2.3): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing phpunit/php-token-stream (1.2.2): Loading from cache
  - Installing phpunit/php-code-coverage (1.2.18): Loading from cache
  - Installing phpunit/phpunit (3.7.x-dev 38709dc): Downloading (100%)
  - Installing twig/twig (v1.32.0): Loading from cache
  - Installing mongodb/mongodb (1.1.2): Loading from cache
  - Installing alcaeus/mongo-php-adapter (1.0.9): Loading from cache
```

**Comment by mobilizer** [comment]
Importing the saved data from the file to mongodb with 

    php external/import.php -f cache/xhgui.data

show following error:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php70-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib
```

Might be some problem with macOS brew version of php70-mongodb.

**Comment by mobilizer** [comment]
Actually it is really a problem with macOS and the brew version of mongodb. 

Following fix works: https://github.com/Homebrew/homebrew-php/issues/3737#issuecomment-279932413

     brew edit php70-mongodb

```
def install
    Dir.chdir "mongodb-#{version}" unless build.head?
    
    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0" 
      inreplace %w[src/libbson/src/bson/bson-clock.c], "HAVE_CLOCK_GETTIME", "UNDEFINED_GIBBERISH"
    end

    ENV.universal_binary if build.universal?

    safe_phpize
    system "./configure", "--prefix=#{prefix}",
                          phpconfig,
                          "--with-openssl-dir=#{Formula["openssl"].opt_prefix}"
    system "make"
    prefix.install "modules/mongodb.so"
    write_config_file if build.with? "config-file"
  end
```

     brew reinstall -s php70-mongodb

**Comment by mobilizer** [comment]
@markstory BTW: Tideways daemon is not required when using XHGui. 

Following settings in ext-tideways.ini work with XHGui:

```
[tideways]
extension="/usr/local/Cellar/php70-tideways/v4.0.7/tideways.so"
tideways.connection=unix:///usr/local/var/run/tidewaysd.sock
tideways.load_library=0
tideways.auto_prepend_library=0
tideways.auto_start=0
tideways.sample_rate=100
```

**Comment by markstory** [comment]
Thanks @mobilizer I'll add that to the readme.

**Comment by glensc** [comment]
closing as being outdated.

profiler install instructions can be found here:
- https://github.com/perftools/php-profiler/#installing-profilers
