### ISSUE TITLE
Why does it show negative number of MemUse?

### ISSUE THREAD

**Issue by qiuyuexi** [perftools/xhgui#200]
![fdc84015-cf72-4326-b93b-a3e4e2895bcd](https://cloud.githubusercontent.com/assets/19420268/24739846/a6e55a5e-1ad0-11e7-8387-0a6ff0ff05e3.png)

the mu show  negative number, and the pmu is zero. l can't understand  what caused it ,could you tell me,thank you!

**Comment by markstory** [comment]
Given the information at hand, I also have no idea. Sometimes a function can reduce memory use if it frees up memory by destroying objects, or other state.

**Comment by qiuyuexi** [comment]
thank you。

**Comment by qiuyuexi** [comment]
I just  include one php file which define 100 constants, sorry , my English is poor
