### ISSUE TITLE
Tideway 4 import fails

### ISSUE THREAD

**Issue by macdabby** [perftools/xhgui#203]
I am using tideways 4.1.2: 6a7a7aaf62f05606a81b447ad09110d081d8cf88

I am able to see the tmp files and they are written in php serialized format. However when i try to import, the import script tries to ready JSON format. I tried to alter that import script to read serialized instead, and it imported into mongo (see below) but it looks like none of the values match up. 

Is xhgui not compatible with this version of tideways? can it be updated? or does this version not collect all the same data as previous versions?

![screen shot 2017-06-20 at 9 54 57 am](https://user-images.githubusercontent.com/176957/27339877-9870e6d8-559e-11e7-8a3d-d0c9cb3df30f.png)

**Comment by markstory** [comment]
>Is xhgui not compatible with this version of tideways? can it be updated? 

I'm not sure. I've never used that version. I'm confident Xhgui could be updated to import that format if someone took the time to do it. I personally don't have much time to dedicate to supporting collectors that don't just work, but if you have interest/time I'm happy to help with reviewing changes and merging the results.

**Comment by michaelbutler** [comment]
the function `tideways_disable` should be backwards compatible, byte for byte, with xhprof_disable. I'm using tideways 4.1.2 with XHGUI and it works, though I am using a custom data dumper & loader.

**Comment by macdabby** [comment]
@michaelbutler is there anywhere i can see sample output of what it should look like? the importer is definitely expecting json and failing because my file is not json but php serialized

**Comment by macdabby** [comment]
@markstory  if this turns out to be a legit issue i'd be happy to work on it - any info you have on the formats and what they are expected to be would be an awesome help

**Comment by gabel** [comment]
@macdabby Even though this is an old topic. The format has to be `json` to work with `import.php` that means you have to convert the php serialized files or save the profile in json format.

Example

```
register_shutdown_function(function () {
    $data = tideways_xhprof_disable();
    file_put_contents(
        sprintf("%s/yourapp.%d.xhprof", sys_get_temp_dir(), getmypid()),
        json_encode($data)
    );
});
```

The result file can now be imported using `import.php -f yourapp.123.xhprof`.

**Comment by glensc** [comment]
@macdabby you should switch to tideways v5, it works for me with PHP 7.3:
- https://github.com/perftools/php-profiler#installing-profilers

@gabel you are talking about the file saver:
- https://github.com/perftools/php-profiler#file-saver
