### ISSUE TITLE
Flamegraph assumes nodes are self-time only

### ISSUE THREAD

**Issue by michaelbutler** [perftools/xhgui#207]
Hello, when using XHGUI with the Flamegraph (the Callgraph view shows correct times) I noticed that the times are inflated very large, something around 8X the actual amount. I debugged it down to happening in JS inside D3. My guess is that D3 is assuming the nodes are self time only, so it's recalculating the total time by recursively adding its children, however XHGUI has already calculated that info. 

For example, my `main()` is 813,000 µs, but in the flamegraph it reports 9,370,000 µs for `main()`.  

This also unfortunately messes up the ratios in the flamegraph, for example the next highest item after `main()` in my case says 72%, however the actual ration should be 90%. 

Has anyone else noticed this? I'm thinking the best way to fix would be in the ajax request for flamegraph data, just return self times for each node not including children.

**Comment by markstory** [comment]
>  I'm thinking the best way to fix would be in the ajax request for flamegraph data, just return self times for each node not including children.

That sounds like a reasonable fix to me.

**Comment by markstory** [comment]
Closing as #216 has more context.
