### ISSUE TITLE
Legibility issues on flame graph

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui#211]
On a typical flame graph I find two problems that impair its usability:

<img width="546" alt="screen shot 2017-10-16 at 16 44 14" src="https://user-images.githubusercontent.com/156867/31621314-49bbd278-b291-11e7-9b5e-a962e853409b.png">

1. The text has a text-shadow applies which makes the text somewhat blurry and rather hard to read.
2. The color contrast between the yellow, orange and reds is very low. The colors look almost identical.

Regarding the text-shadow, I believe this was unintentionally inherited from Bootstrap styles. When inspecting one of the labels, I find it has a `class="label"` and the D3 styles happen to overlap almost all the styles inherited from Boostrap, but not the text-shadow, that one survives. Given that grey shadow was meant for white text originally within Bootstrap, it is now applying to black text and essentially producing a blur.

`.d3-flame-graph .label {` _– from d3.flameGraph_
* `pointer-events: none;`
* `white-space: nowrap;`
* `text-overflow: ellipsis;`
* `overflow: hidden;`
* `font-size: 12px;`
* `font-family: Verdana;`
* `margin-left: 4px;`
* `margin-right: 4px;`
* `line-height: 1.5;`
* `padding: 0 0 0;`
* `font-weight: 400;`
* `color: black;`
* `text-align: left;`

`.label, .badge {` _– from bootstrap.min.css_
* ~~`display: inline-block;`~~
* ~~`padding: 2px 4px;`~~
* ~~`font-size: 11.844px;`~~
* ~~`font-weight: bold;`~~
* ~~`line-height: 14px;`~~
* ~~`color: #ffffff;`~~
* `vertical-align: baseline;`
* ~~`white-space: nowrap;`~~
* **`text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);`**
* ~~`background-color: #999999;`~~

Regarding the flame color contrast, would be good to align closer with [Brendan Gregg](https://github.com/brendangregg/FlameGraph)'s original color scheme:

| d3.flameGraph | brendangregg/FlameGraph
|--|--
| <img width="546" alt="screen shot 2017-10-16 at 16 44 14" src="https://user-images.githubusercontent.com/156867/31621314-49bbd278-b291-11e7-9b5e-a962e853409b.png"> | <img width="427" alt="screen shot 2017-10-16 at 16 51 11" src="https://user-images.githubusercontent.com/156867/31621700-48329a4e-b292-11e7-910e-c186a05fc505.png">

**Comment by Krinkle** [comment]
Regarding the text rendering issue, to confirm - the original demo is not affected <http://martinspier.io/d3-flame-graph/>

This is purely a problem from D3 and Bootstrap ending up on the same page. We could override the styles stronger on our side. But a better solution would be for upstream to use a less generic class name in this case.

**Comment by markstory** [comment]
Any chance you'd be willing to make a pull request with with the proposed changes?

**Comment by Krinkle** [comment]
Note to self:

Updating d3.flameGraph CSS/JS to latest versions is blocked on:

* Deal with local hack 1: 71f521e3d4dfdb7c890619b805f002d02960494b
* Deal with local hack 2: 0ff9af8543e2cd7a3ba6817eb291aa8721334910
* Upgrade d3 from v3.x to v4.x. (Current: 3.0.8, Previously required by flameGraph: 3.5, now required by flameGraph: 4.0)

First error I got on current d3 version is `d3.partition` undefined. Looks like it moved from `d3.layout.partition` to `d3.partition`.
