### ISSUE TITLE
Which version is compatible with `php5-mongo`

### ISSUE THREAD

**Issue by Firesphere** [perftools/xhgui#220]
I'm trying to get this to run with php5-mongo extension instead of phpx.x-mongodb. What version is compatible with that type of installation?

**Comment by markstory** [comment]
Probably 0.6.0 and earlier. After that php7 support was added requiring us to use the newer extension.

**Comment by tm1000** [comment]
@markstory if that is true then the repository should be updated to state that you require php 7 and also reference the newer mongodb library. Currently in the readme it does not

**Comment by tm1000** [comment]
I see the issue. In the readme of this project it is still referencing the older mongo pecl library

**Comment by markstory** [comment]
@tm1000 It probably should, I've just not found time to put that at the top of my list.
