### ISSUE TITLE
tideways is now tideways_xhprof

### ISSUE THREAD

**Issue by boldhedgehog** [perftools/xhgui#222]
Hi,

Tideways PHP profiles extension is now (v5.0) called tideways_xhprof, and they renamed all key functions and constants 5 days ago.

https://github.com/tideways/php-profiler-extension/commit/fc808db5c3df0e4055db612d15224b3acd1eaa88

**Comment by markstory** [comment]
Perhaps we should document that < v5 is required.

**Comment by beberlei** [comment]
@markstory for PHP 7 you should support the new extension if possible, it reduces the overhead significantly and is based on a completly modern C codebase. You can find some info about migrating in the blog post: https://tideways.io/profiler/blog/releasing-new-tideways-xhprof-extension

**Comment by markstory** [comment]
@beberlei Ok.
