### ISSUE TITLE
Output fluentd or fluentbit log collector

### ISSUE THREAD

**Issue by mhf-ir** [perftools/xhgui#226]
If output set to udp or tcp fluentd log collector will be awesome. 
Designing Microservice any log collector like fluentd or logstash can collect logs and buffer it to actual storage like mongo or elastic will be awesome.

**Comment by glensc** [comment]
This belongs to the profiler package now:
- https://github.com/perftools/php-profiler

submit issue (or preferred pull request) there if this is still relevant.
