### ISSUE TITLE
composer.lock file is outdated

### ISSUE THREAD

**Issue by skors** [perftools/xhgui#227]
Hi,

the composer lock file is outdated, for example the perftools/xhgui-collector dependency is missing in it. This result in an error when using the external/header.php into any project:

`Warning: require_once(/opt/xhgui/vendor/perftools/xhgui-collector/external/header.php): failed to open stream: No such file or directory in /opt/xhgui/external/header.php on line 9`

**Comment by markstory** [comment]
I'm going to remove the lock file. This project supports too many versions of PHP to bundle one reliably.

**Comment by skors** [comment]
thanks for the quick response!
