### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages during php install.php

### ISSUE THREAD

**Issue by w7089** [perftools/xhgui#229]
Getting the error in apache error log:

`PHP Fatal error:  require_once(): Failed opening required '/var/www/html/xhgui/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/xhgui/external/header.php on line 6`

After accessing website with prepended _/var/www/html/xhgui/external/header.php_

I guess _xhgui_ installer failed. Below is the output of running _php install.php:_ 

> Composer already installed.
> Installing dependencies.
> ERROR - Cannot create cache directory /home/me/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
> Cannot create cache directory /home/me/.composer/cache/files/, or directory is not writable. Proceeding without cache
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - alcaeus/mongo-php-adapter 1.0.0 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.1 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.10 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.11 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.2 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.3 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.4 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.5 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.6 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.7 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.8 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.0.9 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0].
>     - alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - alcaeus/mongo-php-adapter 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - alcaeus/mongo-php-adapter 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - alcaeus/mongo-php-adapter 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.5 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - Installation request for alcaeus/mongo-php-adapter ^1.0 -> satisfiable by alcaeus/mongo-php-adapter[1.0.0, 1.0.1, 1.0.10, 1.0.1
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - /etc/php/7.0/cli/php.ini
>     - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
>     - /etc/php/7.0/cli/conf.d/10-opcache.ini
>     - /etc/php/7.0/cli/conf.d/10-pdo.ini
>     - /etc/php/7.0/cli/conf.d/15-xml.ini
>     - /etc/php/7.0/cli/conf.d/20-calendar.ini
>     - /etc/php/7.0/cli/conf.d/20-ctype.ini
>     - /etc/php/7.0/cli/conf.d/20-curl.ini
>     - /etc/php/7.0/cli/conf.d/20-dom.ini
>     - /etc/php/7.0/cli/conf.d/20-exif.ini
>     - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
>     - /etc/php/7.0/cli/conf.d/20-ftp.ini
>     - /etc/php/7.0/cli/conf.d/20-gd.ini
>     - /etc/php/7.0/cli/conf.d/20-gettext.ini
>     - /etc/php/7.0/cli/conf.d/20-iconv.ini
>     - /etc/php/7.0/cli/conf.d/20-json.ini
>     - /etc/php/7.0/cli/conf.d/20-mbstring.ini
>     - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
>     - /etc/php/7.0/cli/conf.d/20-mysqli.ini
>     - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
>     - /etc/php/7.0/cli/conf.d/20-phar.ini
>     - /etc/php/7.0/cli/conf.d/20-posix.ini
>     - /etc/php/7.0/cli/conf.d/20-readline.ini
>     - /etc/php/7.0/cli/conf.d/20-shmop.ini
>     - /etc/php/7.0/cli/conf.d/20-simplexml.ini
>     - /etc/php/7.0/cli/conf.d/20-sockets.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
>     - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
>     - /etc/php/7.0/cli/conf.d/20-wddx.ini
>     - /etc/php/7.0/cli/conf.d/20-xdebug.ini
>     - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
>     - /etc/php/7.0/cli/conf.d/20-xmlrpc.ini
>     - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
>     - /etc/php/7.0/cli/conf.d/20-xsl.ini
>     - /etc/php/7.0/cli/conf.d/20-zip.ini
>     - /etc/php/7.0/cli/conf.d/40-tideways_xhprof.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> Checking permissions for cache directory.
> Permissions on cache/ are ok.
> 

Would be happy to understand what's wrong. I'm using Tideways + PHP7.0 on Kubuntu 16.04
Regards

**Comment by markstory** [comment]
Do you have a mongodb extension installed?

**Comment by PrinzJuliano** [comment]
I got the warning by composer that the `composer.lock` file does not match the `composer.json` and thus it exits without creating a vendor directory!

**Comment by PrinzJuliano** [comment]
I receive the same issue in a docker container built on Jan 15th 2018.

**Comment by PrinzJuliano** [comment]
This however results in this message on the start page:
```
Fatal error: Uncaught TypeError: Argument 3 passed to MongoDB\Driver\Server::executeQuery() must be an instance of MongoDB\Driver\ReadPreference or null, array given in /opt/xhgui/vendor/mongodb/mongodb/src/Operation/Find.php:287 
Stack trace: 
#0 /opt/xhgui/vendor/mongodb/mongodb/src/Operation/Find.php(287): MongoDB\Driver\Server->executeQuery('xhprof.results', Object(MongoDB\Driver\Query), Array) 
#1 /opt/xhgui/vendor/mongodb/mongodb/src/Operation/FindOne.php(124): MongoDB\Operation\Find->execute(Object(MongoDB\Driver\Server)) 
#2 /opt/xhgui/vendor/mongodb/mongodb/src/Collection.php(563): MongoDB\Operation\FindOne->execute(Object(MongoDB\Driver\Server)) 
#3 /opt/xhgui/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(561): MongoDB\Collection->findOne(Array, Array) 
#4 /opt/xhgui/src/Xhgui/Saver.php(24): MongoCollection->findOne() 
#5 /opt/xhgui/vendor/perftools/xhgui-collector/external/header.php(174): Xhgui_Saver::factory(Array) 
#6 [internal function]: {closure}() 
#7 {main} thrown in /opt/xhgui/vendor/mongodb/mongodb/src/Operation/Find.php on line 287
```

**Comment by yoh** [comment]
I install the php mongo extension requirement (`sudo apt-get install php-mongodb`on debian) and it solve this problem.
