### ISSUE TITLE
Sqlite backend support

### ISSUE THREAD

**Issue by 1ma** [perftools/xhgui#234]
I really like xhgui, but I find it a bit ridiculous that it needs a MongoDB daemon to function. If I were to refactor the `Profiles` class so that it were able to persist and read either from Mongo or an Sqlite3 database, would you be interested in a PR for that?

The behaviour would still be controlled with the `save.handler` option (say, by setting it to `sqlite`) and `save.handler.filename`, that would point to the database file.

**Comment by markstory** [comment]
I would be ok with moving off of mongodb. I find it painful to operate and its use has created a bunch of complexity around aggregation and summary data.

Instead of going to 'just' SQLite, we could use a database abstraction layer like cakephp/database to enable the use of postgres/sqlite/mysql with relative ease.

**Comment by 1ma** [comment]
Yup. Well, I've just started to peek at the code, but as of now my tentative plan would be more or less:

1. Extract an interface from `MongoDB`
2. Create a "dummy" class that extends `MongoDB` and implements said interface
3. Replace `MongoDB` with said interface in the [`Profiles` constructor](https://github.com/perftools/xhgui/blob/b2440c1488691ba4d2ccd698bb7661ac0e3fbe99/src/Xhgui/Profiles.php#L11), and inject the new dummy class.
4. Implement any other backends (SQLite/MySQL/Postgres whatever) as instances of that interface, and dynamically choose the one in use with the current config mechanism.
5. Clean up the interface of any methods that `Profiles` do not need.

What do you think?

**Comment by markstory** [comment]
That sounds like it could work well.

**Comment by GrzegorzDrozd** [comment]
Any update on this ?

**Comment by 1ma** [comment]
Since I opened the ticket I forked the project and made a couple of small contributions to get acquainted with the project (#235, #236). Then life happened and I stalled, but I intend to get back on this.

This is the feature branch: https://github.com/1ma/xhgui/tree/backend-decoupling Design-wise, I now intend to extract an interface from `Profiles` instead of `MongoDB` because it is very highly coupled to MongoDB, but at the same time all database interactions are nicely tucked away inside that class.

**Comment by 1ma** [comment]
Quick update: I resumed this task a few days ago. As of now, the `xhgui-collector` can store profiles in SQLite and `xhgui` can retrieve the summary to print them in the home page. Still quite a long way to go, though.

**Comment by GrzegorzDrozd** [comment]
My PR with different storage engines is here: https://github.com/perftools/xhgui/pull/273

**Comment by glensc** [comment]
Seems @GrzegorzDrozd work in https://github.com/perftools/xhgui/pull/273 (open) overwrites changes done in: https://github.com/perftools/xhgui/pull/244 (merged)

For example:
- `Xhgui_Searcher_Interface` -> `Xhgui_Profiles`

But https://github.com/perftools/xhgui/pull/244 summarizes:
- `Xhgui_Profiles` was renamed to `Xhgui_Searcher_Mongo` and an interface (`Xhgui_Searcher_Interface`) was extracted from it.

perhaps it was dated before https://github.com/perftools/xhgui/pull/244 was merged

it also contains tons of other irrelevant changes stuffed to single pull request

**Comment by glensc** [comment]
closing this as https://github.com/perftools/xhgui/pull/244 is merged
