### ISSUE TITLE
tideways: Undefined index: cpu

### ISSUE THREAD

**Issue by glensc** [perftools/xhgui#240]
Using [Tideways](https://github.com/tideways/php-xhprof-extension) extension.

collecting seems fine, but can't view individual details with 0.9.0 (or 0.8.1)

```
➔ composer.phar show -p|grep tide
ext-tideways         4.1.6    The tideways PHP extension
```

could include more details. just wanted the bugreport out there first.

**Comment by markstory** [comment]
I'll see if I can reproduce.

**Comment by glensc** [comment]
outdated
