### ISSUE TITLE
Call to undefined method Xhgui_Profile::getSQL()

### ISSUE THREAD

**Issue by tomlinux** [perftools/xhgui#247]
php5.6.31  

[root@centos7 ~]# php --ri xhprof
xhprof
xhprof => 0.9.2
CPU num => 4
![image](https://user-images.githubusercontent.com/16485766/48774023-f8d20b80-ed03-11e8-9741-f78fb345dbee.png)

日志显示错误：
018/11/20 19:35:50 [error] 2104#0: *2739453 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f1692c18b63e712585eb HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn"
2018/11/20 19:35:52 [error] 2104#0: *2739453 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f1692c18b63e712585eb HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn"
2018/11/20 19:42:13 [error] 2104#0: *2747355 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf395772c18b66f69674ab2 HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn", referrer: "http://t2.556q0.cn/url/view?url=%2Fa.php"
2018/11/20 19:42:17 [error] 2104#0: *2747355 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf395772c18b66f69674ab2 HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn"
2018/11/20 19:55:04 [error] 2104#0: *2769560 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f60c2c18b63fa86458dc HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn", referrer: "http://t2.556q0.cn/url/view?url=%2Fmanage_Channel_editAccountStatus.html"
2018/11/20 19:55:07 [error] 2104#0: *2769560 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f60c2c18b63fa86458dc HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn", referrer: "http://t2.556q0.cn/url/view?url=%2Fmanage_Channel_editAccountStatus.html"
2018/11/20 19:55:11 [error] 2104#0: *2769560 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f60c2c18b63fa86458dc HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn", referrer: "http://t2.556q0.cn/url/view?url=%2Fmanage_Channel_editAccountStatus.html"
2018/11/20 20:13:15 [error] 2105#0: *2805645 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f60c2c18b63fa86458dc HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn", referrer: "http://t2.556q0.cn/url/view?url=%2Fmanage_Channel_editAccountStatus.html"
2018/11/20 20:14:50 [error] 2104#0: *2809643 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116" while reading response header from upstream, client: 115.196.175.235, server: t2.556q0.cn, request: "GET /run/view?id=5bf3f5d82c18b63e6c027cfb HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "t2.556q0.cn", referrer: "http://t2.556q0.cn/url/view?url=%2Fmanage_Channel_account_pid_201.html%3Frows%26__hash__dd8591389441b953c12a7412c1ceb68_649193fdba681304455c1e4803e98bb4"

**Comment by markstory** [comment]
Have you tried updating your copy of Xhgui? The line in your error logs

```
 "PHP message: PHP Fatal error: Call to undefined method Xhgui_Profile::getSQL() in /data02/wwwroot/xhgui/src/Xhgui/Controller/Run.php on line 116"
```

Does not exist in [current master](https://github.com/perftools/xhgui/blob/master/src/Xhgui/Controller/Run.php#L116)

**Comment by glensc** [comment]
Problem caused by outdated code, or locally modified xhgui installation
