### ISSUE TITLE
Add read-only mode for the web interface

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui#248]
The last release introduced the first write operations in the web interface (as far as I know).

Specifically:
* Delete a run.
* Delete all runs.
* Upload a run (import).

Given that Wikimedia runs a public XHGui instance, we'll need a way to disable these routes so as to avoid accidental and/or abusive write actions.

**Comment by markstory** [comment]
Sounds like a good idea to me :+1: Could it be a configuration setting to enable the read-only mode?

**Comment by Krinkle** [comment]
@markstory Yep, makes sense.

**Comment by markstory** [comment]
Using POST for write operations is a good practice to follow anyways. Thank you for opening a pull request to fix that mistake. If your requirements for having a read-only xhgui are solved by moving all the writes to POST/PUT/DELETE then perhaps we don't need an additional configuration variable. Folks deploying xhgui tend to have a bit more control over their environments.
