### ISSUE TITLE
xhgui won't work with PHP 7.3 because of tideways_xhprof

### ISSUE THREAD

**Issue by hAtul89** [perftools/xhgui#260]
Following this tutorial - installing xhgui with tideways: 
http://divyanshu-techbook.strikingly.com/blog/xhgui-for-ubuntu-with-php-7

I added the files: 
```
sudo vim /etc/php/7.2/mods-available/tideways.ini
sudo vim /etc/php/7.3/mods-available/tideways.ini 
```
With the content of: 
```
extension=tideways_xhprof.so
``` 
(and not `extension=tideways.so` as mentioned in the tutorial... )
running `php -v` outputs: 
``` 
PHP Warning:  PHP Startup: tideways_xhprof: Unable to initialize module
Module compiled with module API=20170718
PHP    compiled with module API=20180731
These options need to match
 in Unknown on line 0
PHP 7.3.2-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:43:57) ( NTS )
```

`php --ri tideways` returns: 
``` 
PHP Warning:  PHP Startup: tideways_xhprof: Unable to initialize module
Module compiled with module API=20170718
PHP    compiled with module API=20180731
These options need to match
 in Unknown on line 0
Extension 'tideways' not present.
``` 

The file: `/usr/lib/php/20180731/tideways_xhprof.so` exits for sure under this directory. 

Is this a bug?

**Comment by markstory** [comment]
Seems like an issue with tideways and not xhgui.

**Comment by lauripiisang** [comment]
It seems to me that you are unable to load tideways_xhprof extension in PHP, this has nothing to do with xhgui. 
Xhgui merely processes the output of said exentsion. 
The error would suggest that you have to load tideways.so as well.
