### ISSUE TITLE
Discourage caching of run lists

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui#261]
At Wikimedia Foundation we use XHGui to store Tideways-xhprof profiles from "debug" requests (request where, via a special header enabled via a browser extension, you opt-in to a full call graph and then internally submitting it to database that the public XHGui instance reads from).

All web services by default (including XHGui) pass through a CDN layer for caching and flood protection (Varnish Cache). Due to this, and XHGUi not sending any Cache-Control header, it means that the XHGui index page with recent runs, generally never shows the the run I just recorded. This because the default assumption (both in browsers and in Varnish) is that if no CC is set, we assume "public" and reuse it based on various heuristics. In our cache that means a fallback TTL for 24 hours.

I'd like to add some Cache-Control headers and propose the following:

* Index page, run lists, search results: `Cache-Control: public, max-age=0`. This means browsers may cache it when e.g. backwards-forwards navigating, and the CDN may re-use it for concurrent requests and other edge cases. But generally, it will not be re-used beyond initial generation. In the future, if we're worried about the size of the HTML, we could use E-Tag or Last-Modified to allow the browser and CDN to get a 304 Not Modified upon revalidation, instead of a full copy, but that's probably not worth doing right now.

* Pages about individual runs: `Cache-Control: public, max-age=60`. Allow a bit more caching given the data is meant to be immutable. But, to avoid annoying situations where e.g. after a deployment things are all outdated or misplaced with regards to scripts and styles, still limit it to 1 minute to allow for quick propagation. If and when we find there are high-traffic consumers that are worried about response times for individual runs, we could make this configurable.

* Static files: These are served by Apache or other web server used, so it's up to the site admin to configure this.

For example, for Apache one could use:

```
<IfModule mod_expires.c>
   ExpiresActive On
   <Directory ~ "^/srv/xhgui/webroot">
        <FilesMatch "\.(css|js|gif|png|svg|json|ttf|woff|woff2)$">
            ExpiresByType text/css A31536000
            ExpiresByType text/javascript A31536000
            ExpiresByType application/x-javascript A31536000
            ExpiresByType image/gif A31536000
            ExpiresByType image/png A31536000
            ExpiresByType image/svg+xml A31536000
            ExpiresByType application/json A31536000
            ExpiresByType application/x-font-ttf A31536000
            ExpiresByType application/font-woff A31536000
            ExpiresByType application/font-woff2 A31536000
            Header add Access-Control-Allow-Origin "*"
        </FilesMatch>
    </Directory>
</IfModule>
```

And we could include an htaccess-compatible version in the repo as well.

**Comment by Krinkle** [comment]
@markstory If you approve of this, could you point me in the right direction on where to add this?

**Comment by markstory** [comment]
This all sounds reasonable to me. There is an existing [.htaccess](https://github.com/perftools/xhgui/blob/master/webroot/.htaccess) config file. If you'd prefer we could update the application endpoints to emit the Cache-Control headers as well.
