### ISSUE TITLE
Remove string from all the URLs

### ISSUE THREAD

**Issue by Mte90** [perftools/xhgui#262]
![immagine](https://user-images.githubusercontent.com/403283/54626878-67389780-4a72-11e9-805b-96c6f0eeeb30.png)
As the screen there is this parameter in the URL but I want that is removed or atleast not showed because is useless.

**Comment by Mte90** [comment]
I was trying to implement that with a custom function in `config.php` and add a  `function_exists` check to run.
Anyway in twig file this funciton not exists in that way.
There is a way to pass a function in the config array? 
I see that this data is generated by Mongo so there is no way to hook and change them.
@markstory do you have any suggestion?

**Comment by markstory** [comment]
If you are hoping to remove data from the result data wouldn't it be simpler to do that before a run is saved?

**Comment by Mte90** [comment]
I was thinking that is better to have all the data in the system and later to not show them but after all this tool has a "Delete all" feature so this is not a problem.
I will check how to execute it before to save the data.

**Comment by Mte90** [comment]
and #24 is here :-)

**Comment by Krinkle** [comment]
I suppose this ticket can be closed now :)
