### ISSUE TITLE
database part of mongodb url is not handled

### ISSUE THREAD

**Issue by athoune** [perftools/xhgui#267]
In `config.default.php`

```
 'db.host' => getenv('XHGUI_MONGO_HOST') ?: 'mongodb://127.0.0.1:27017',
 'db.db' => getenv('XHGUI_MONGO_DATABASE') ?: 'xhprof',
```
The mongodb url pattern is `mongodb://user:password@server/database?options`.
So, the url is enough, and setting can be done with just one environment.

Side effect : when you mess with database, mongodb doesn't care, and just wait for writing in your wrong database. It's a silent error.

**Comment by glensc** [comment]
It's difficult to support such configuration, this would mean xhgui needs to parse on its own 'db.host' dsn to extract database name from it.

There doesn't seem to be a method to fetch default database from `$mongo` connection:
- https://github.com/perftools/xhgui/blob/0.16.2/src/Xhgui/ServiceContainer.php#L106-L107

**Comment by glensc** [comment]
Perhaps better approach is to refactor to use different structure:

```php
 'mongo.hostname' => getenv('XHGUI_MONGO_HOSTNAME') ?: '127.0.0.1',
 'mongo.port' => getenv('XHGUI_MONGO_PORT') ?: '27017',
 'mongo.database' => getenv('XHGUI_MONGO_DATABASE') ?: 'xhprof',
```

and build the DSN style variable in the code.
