### ISSUE TITLE
Unable to install composer dependencies on PHP 5.6 with ext-mongo

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui#271]
I'm upgrading a legacy install from xhgui's master on January 9th this year to the latest master, and facing an issue where I'm unable to satisfy Composer in a way that it will install dependencies.

The server in question has PHP 5.6 with ext-mongo natively installed, which XHGui supports (and technically even prefers, given it simulates this older library on top of the newer ext-mongodb).

This can be reproduced by adding the following to xhgui/composer.json:
```
{
    "config": {
        "platform": {
            "php": "5.6.40",
            "ext-mongo": "1.5.7"
        }
    },
   …
```

And then run `composer install --prefer-dist --no-dev`. This fails as follows:

```
  Problem 1
    - alcaeus/mongo-php-adapter 1.1.7 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - …
    - alcaeus/mongo-php-adapter 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for alcaeus/mongo-php-adapter ^1.1 -> satisfiable by alcaeus/mongo-php-adapter[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7].
```

What I understand so far:

* `alcaeus/mongo-php-adapter` is not specified as a requirement. But, composer still insists on building a valid tree for all associated dependencies, including require-dev packages.
* mongo-php-adapter v1.1.0 and later requires `ext-mongodb` with either PHP 5.x or PHP 7.x (this is generally for PHP 7). It no longer works if `ext-mongo` is already provided by the system, it seems.
* mongo-php-adapter v1.0.11 and earlier was tolerant to this.

**Comment by Krinkle** [comment]
I've tried changing the require-dev declaration as follows:

```diff
-  "alcaeus/mongo-php-adapter": "^1.1",
+  "alcaeus/mongo-php-adapter": "^1.0",
```

But that instead produces the following error:

```
  Problem 1
    - alcaeus/mongo-php-adapter 1.0.0 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.1, 1.4.2].
    - …
    - alcaeus/mongo-php-adapter 1.0.9 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.1, 1.4.2].
    - alcaeus/mongo-php-adapter 1.1.7 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - …
    - alcaeus/mongo-php-adapter 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.4.2 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
    -…
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for alcaeus/mongo-php-adapter ^1.0 -> satisfiable by alcaeus/mongo-php-adapter[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7].
```

This then results in the lower level `mongodb/mongodb` package complaining about ext-mongodb, which is only meant to be triggered when `ext-mongodb` is present.

**Comment by Krinkle** [comment]
I've found a workaround for now by fooling composer that `ext-mongodb` is installed, despite this not being true.

```json
{
    "config": {
        "platform": {
            "php": "5.6.40",
            "ext-mongodb": "1.999"
        }
    },
```

This will probably fall apart at some point, but at least for now it seems nothing is depending on this yet in ways that causes issues. It installs the right dependencies and cursory testing of the instance shows it works fine.

**Comment by glensc** [comment]
you may more useful to jus use docker based install:
- https://github.com/perftools/xhgui/#installation-with-docker

**Comment by Krinkle** [comment]
I suggest we drop PHP 5.6 support in that case. Thisi is no longer an issue for Wikimedia (we run the latest XHGui only  on PHP7).

**Comment by Krinkle** [comment]
> I suggest we drop PHP 5.6 support in that case.

This is now being done at https://github.com/perftools/xhgui/pull/307.
