### ISSUE TITLE
Docker install: how do I get the vendor/autoload.php and vendor/perftools/xhgui-collector/external/header.php files?

### ISSUE THREAD

**Issue by therealgilles** [perftools/xhgui#276]
I am trying to use xhgui with tideways on mac os x 10.15. I used the docker instructions and the webserver came up. But I am not sure how to get access to the vendor files necessary to enable profiling with my php app.

Thank you for any guidance.

**Comment by therealgilles** [comment]
I ran this to extract the files from docker:

```docker cp <xhgui_app_container_id>:var/www/xhgui/vendor vendor```

Is that the way to go?

**Comment by therealgilles** [comment]
The 'wt' (wall time) parameter shows 0, so something must be amiss.

**Comment by markstory** [comment]
You don't extract the header file. Instead you can use the xhgui-collector package in your application. The dockerfilenis more for hosting the gui.

**Comment by flip111** [comment]
This happens because on startup you get to see

> Looks like you haven't done any profiling
>
> To get started with XHGUI you'll need to collect some profiling data.
>
> The simplest way to get an application profiled, is to use external/header.php. This file is designed to be combined with PHP's auto_prepend_file directive. This can be enabled system-wide through php.ini. Alternatively, you can enable auto_prepend_file per virtual host. See the README.md file for more details.

Then you include the `header.php` file, but this one is from the "normal" non-dockerized source code. At the moment no method has been described in the readme how to get profile information into the docker container.



> Instead you can use the xhgui-collector package in your application

I don't understand this comment. Even with using this package you still have the situation that your app is outside of the container, and xhgui + it's mongodb instance is inside the container. Possibly mongodb has a port open so you can put information inside it. But how? Including a `header.php` file sounded nice and easy ...

**Comment by glensc** [comment]
for saving samples, I recommend using the new package:
- https://github.com/perftools/php-profiler

and yes, of course, it needs access to the same MongoDB instance, where GUI reads the data.

how you manage to do that depends very much on your setup. 

If you have ideas for documentation update, PR's are most welcome :)

ps: you quote text, which is not from this issue (https://github.com/perftools/xhgui/issues/276). it's confusing as hell as well.

**Comment by flip111** [comment]
The main problem is getting data into the database, not to get it out.

> ps: you quote text, which is not from this issue (#276). it's confusing as hell as well.

This issue is #276 maybe you are mixing up issues?

**Comment by glensc** [comment]
@flip111 What I tried to say, is that you quote text which origin is unclear:

> Instead you can use the xhgui-collector package in your application

**Comment by glensc** [comment]
there's documentation update going on, you're welcome to review it: https://github.com/perftools/xhgui/pull/293

**Comment by flip111** [comment]
> @flip111 What I tried to say, is that you quote text which origin is unclear:
> 
> > Instead you can use the xhgui-collector package in your application

The origin is here https://github.com/perftools/xhgui/issues/276#issuecomment-535276320

**Comment by glensc** [comment]
docs merged, you should use the recommended library:
- https://github.com/perftools/xhgui#profiling-a-web-request-or-cli-script
