### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by glensc** [perftools/xhgui#285]
0.9.0 was released Nov 15, 2017, there are 120 commits to master since this tag.

We should make a new release, so that the project does not look stale and the new changes can be used.

# Merged branches

- Merge pull request #244 from 1ma/backend-decoupling
- Merge pull request #279 from FreeLSD/patch-1
- Merge pull request #280 from researchgate/driveroptions
- Merge pull request #215 from Krinkle/flamegraph
- Merge pull request #219 from perftools/flamegraph-data
- Merge pull request #223 from beberlei/TidewaysXhprof
- Merge pull request #224 from perftools/use-collector
- Merge pull request #225 from Ruesin/master
- Merge pull request #228 from skors/fix/#221_mongodb_cursor
- Merge pull request #233 from tm1000/patch-1
- Merge pull request #235 from 1ma/absolute-paths
- Merge pull request #236 from 1ma/resolve-cp-conflicts
- Merge pull request #230 from comandi/add-profile-import-over-network
- Merge pull request #238 from dumityty/delete-runs
- Merge pull request #239 from dumityty/delete-all-runs
- Merge pull request #242 from 1ma/fix-aggregate-call
- Merge pull request #243 from Mte90/patch-1
- Merge pull request #246 from Krinkle/rm-flamegraph
- Merge pull request #249 from Krinkle/config
- Merge pull request #250 from Krinkle/rm-unused-twig
- Merge pull request #251 from Krinkle/restore-twig
- Merge pull request #254 from Krinkle/fail-pass
- Merge pull request #252 from Krinkle/post-deleteall
- Merge pull request #255 from Krinkle/tests
- Merge pull request #256 from Krinkle/coverage
- Merge pull request #257 from Krinkle/post-delete
- Merge pull request #263 from glensc/docker-stab2
- Merge pull request #264 from Mte90/patch-2
- Merge pull request #265 from Mte90/filter-methods
- Merge pull request #270 from Krinkle/runslist-cc
- Merge pull request #272 from guygaver/guygaver/fix-typos-in-readme
- Merge pull request #277 from panychek/feature/skip-built-in
- Merge pull request #282 from flip111/patch-1
- Merge pull request #284 from 1ma/pdo-env-vars

**Comment by glensc** [comment]
@markstory do you have any checklist of goals what should be solved before 0.10.0 is tagged?

**Comment by Krinkle** [comment]
Perhaps it's time for 1.0?

**Comment by markstory** [comment]
> do you have any checklist of goals what should be solved before 0.10.0 is tagged?

No. I've not had much time to devote to this project lately. I'm happy to do a 1.0 release as I think the current state is pretty stable. The next big changes are likely to do large dependency upgrades and potentially stop using mongodb.

Mongodb has long been challenging as many users are not familiar with operating it, and I think for what this project does mongo isn't a great fit. There have been several pull requests to add additional storage adapters, and entirely work around folks not wanting to operate mongodb. This all leads me to believe that other simpler storage systems may be a better fit.

**Comment by glensc** [comment]
@Krinkle I'd rather polish the multiple backend support a bit. i.e so that the xhgui stays closed box solution that you operate over HTTP via the new client library:
- https://github.com/perftools/php-profiler

using pdo, mongo, etc seems un-neccessary difficulty if you just want to measure your application. 

having client layer thin, I don't think people care what xhgui uses internally. just launch the docker container and don't worry about it.

**Comment by Krinkle** [comment]
That'd be cool yeah, would reduce coupling I suppose. Although it does mean that the XHGui server would no longer be read-only and cleanly isolated network-wise, which is something I currently enjoy, but I'd probably prefer the HTTP solution indeed.

Would adding that API be a breaking change though? Or would it be something we add-on in a minor release?

**Comment by markstory** [comment]
> having client layer thin, I don't think people care what xhgui uses internally. just launch the docker container and don't worry about it.

I don't think 'run and forget' is viable for production and most pre-production environments outside of local development.

Supporting both a document store and SQL based storage solutions makes future changes harder as contributors need to be aware of the nuances of both. It also impedes feature work as new features would need to be compatible with both storage models, and often sql/mongo have conceptual differences that are hard to reconcile.

**Comment by markstory** [comment]
I published 0.10.0, we can always do a 1.0.0 in a bit if things are feeling more settled for other folks.

**Comment by glensc** [comment]
All right. Thanks for finishing this!
