### ISSUE TITLE
PDO initialization issue

### ISSUE THREAD

**Issue by mkolyn** [perftools/xhgui#296]
File: src/Xhgui/ServiceContainer.php
Line: 93
Issue: wrong parameters when calling PDO initialization (the second parameter must be a user, third one - a password)
![pdo-init-issue](https://user-images.githubusercontent.com/3929696/87433895-84439300-c5f2-11ea-9218-78e800357f6b.png)
![pdo-init](https://user-images.githubusercontent.com/3929696/87433927-8ad20a80-c5f2-11ea-853e-108662de5a5e.png)

**Comment by glensc** [comment]
@mkolyn so send a [Pull Request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) with a fix!
