### ISSUE TITLE
docker-compose not work

### ISSUE THREAD

**Issue by laokan** [perftools/xhgui#300]
`Step 10/25 : COPY --from=composer:1.8 /usr/bin/composer /usr/bin/
1.8: Pulling from library/composer
c9b1b535fdd9: Pull complete
c1c0a1817bec: Pull complete
cdd5b3ea1fc3: Pull complete
db87396003bd: Pull complete
ff6d460d7b33: Pull complete
65eb6d20c777: Pull complete
8c0455ae8de1: Pull complete
cb8921b52d2e: Pull complete
27936edf200c: Pull complete
0936bdd4591d: Pull complete
b3a3a25cf032: Pull complete
34d1f7dd062a: Pull complete
6669e41aa073: Pull complete
71efd204dd31: Pull complete
c09156f3cd16: Pull complete
Digest: sha256:08b0f299eff421f8daa48878deaf86f3f7790858c6b139935e657d7b7f1a3e1e
Status: Downloaded newer image for composer:1.8
 ---> af01504c2ab2
Step 11/25 : COPY --from=source /app/composer.* ./
 ---> 9ca433b8e916
Step 12/25 : COPY --from=source /app/vendor ./vendor
 ---> 20e49a6ad02f
Step 13/25 : RUN composer require --update-no-dev --no-scripts alcaeus/mongo-php-adapter ^1.1
 ---> Running in 98b28bb7864a
Do not run Composer as root/super user! See https://getcomposer.org/root for details

  [Composer\Downloader\TransportException]
  The "https://packagist.org/p/provider-2017%24da55a9a05eb278d058d262bec0cbe08c5aecc2b03a1e8e25a34749e67d6d4b6d.json" file could not be downloaded (HTTP/1.1 404 Not Found)

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

ERROR: Service 'app' failed to build: The command '/bin/sh -c composer require --update-no-dev --no-scripts alcaeus/mongo-php-adapter ^1.1' returned a non-zero code: 255`

**Comment by glensc** [comment]
temporary error. can't reproduce.


```
Step 13/25 : RUN composer require --update-no-dev --no-scripts alcaeus/mongo-php-adapter ^1.1
 ---> Running in 3aec28a6605b
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 9 installs, 0 updates, 0 removals
  - Installing slim/slim (2.6.3): Downloading (100%)
  - Installing slim/views (0.1.3): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.18.0): Downloading (100%)
  - Installing twig/twig (v1.43.0): Downloading (100%)
  - Installing pimple/pimple (v1.1.1): Downloading (100%)
  - Installing paragonie/random_compat (v9.99.99): Downloading (100%)
  - Installing perftools/xhgui-collector (1.8.0): Downloading (100%)
  - Installing mongodb/mongodb (1.6.1): Downloading (100%)
  - Installing alcaeus/mongo-php-adapter (1.1.11): Downloading (100%)
Writing lock file
Generating autoload files
Removing intermediate container 3aec28a6605b
```

if the problem persists, you may need to contact https://packagist.org/ support, not here.
