### ISSUE TITLE
Support basic url filter with PDO backend

### ISSUE THREAD

**Issue by Krinkle** [perftools/xhgui#303]
The workflow for Wikimedia's XHGui is to instrument a page load, and then get a link to `https://xhgui/?url=<requestID>` ([example](https://performance.wikimedia.org/xhgui/?url=3687efbd-ccda-4859-8dbe-0ab4e65a98b1)), which yields one result, and is the one the user is interested in.

With the new PDO backend, it seems none of the search options are implemented yet, so this currently leads to all results. This is particularly challenging since a single page load tends to spawn multiple request and thus it'd require the developer to look at the request ID that XHGui is searching for and compare it against the top 20 results or so by eye.

There's more to be done in this area, but I'm filing this one separately so that perhaps Wikimedia can help implement this one, and/or to report back if we find another way :)

**Comment by markstory** [comment]
Getting the PDO backend up to a place where it can replace the mongodb backend would be great. I think the PDO backends will make xhgui easier to get going and simpler to operate.
