### ISSUE TITLE
Dockerfile update

### ISSUE THREAD

**Issue by DmitryOb** [perftools/xhgui#314]
After this commit https://github.com/perftools/xhgui/commit/0b802595dd3f9803e61e5fbc94a715948fa69cb1 
Building docker image are failed linked with this row in dockerfile:
`RUN composer require --update-no-dev --no-scripts alcaeus/mongo-php-adapter ^1.1`

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pimple/pimple (locked at v1.1.1, required as ^3.3) is satisfiable by pimple/pimple[v1.1.1] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Please update Dockerfile

**Comment by glensc** [comment]
@DmitryOb please include reason for closing
