### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, class 'Xhgui_Util' does not have a method 'simpleUrl'

### ISSUE THREAD

**Issue by Mte90** [perftools/xhgui#318]
I am getting this when I press the filter button.
```
<br />
<b>Fatal error</b>:  Uncaught ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Xhgui_Util' does not have a method 'simpleUrl' in /srv/www/default/xhgui/cache/86/869585207f2d4f65fb68730af0fab28d32cda09b31197fb1f76445424e1c21d0.php:72
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(2, 'call_user_func_...', '/srv/www/defaul...', 72, Array)
#1 /srv/www/default/xhgui/cache/86/869585207f2d4f65fb68730af0fab28d32cda09b31197fb1f76445424e1c21d0.php(72): call_user_func_array('Xhgui_Util::sim...', Array)
#2 /srv/www/default/xhgui/vendor/twig/twig/src/Template.php(214): __TwigTemplate_68d7e56ea2bc06fb26a320b08470fb4b11001656f438c1279c621237250796d8-&gt;block_content(Array, Array)
#3 /srv/www/default/xhgui/cache/68/6810bd91e5657d5b8da4a13117720c0c172f6389a2e1388d29cdb30731dec46e.php(125): Twig\Template-&gt;displayBlock('content', Array, Array)
#4 /srv/www/default/xhgui/vendor/twig/twig/src/Template.php(453): __TwigTemplate_b047ad363ac99ac592a287d7918242e53402d46e0b3b589ffaaffe23a3968cdf-&gt;doDispla in <b>/srv/www/default/xhgui/src/templates/runs/view.twig</b> on line <b>17</b><br />
```

To fix it I changed https://github.com/perftools/xhgui/blob/master/src/templates/runs/view.twig#L17 with:
```
<li><strong>URL</strong> <a href="{{ url('url.view', {'url': result.meta('simple_url') }) }}">{{ result.meta('url') }}</a></li>
```

But before to do a pr I prefer to know if also this it will be removed.
I think that the issue is there https://github.com/perftools/xhgui/blob/7d22da694c8f9a6e45f6cc82f168a05a253a3817/src/Xhgui/Twig/Extension.php#L41 that refer to a method of a class that doesn't exist anymore.

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by Mte90** [comment]
Thanks for the hints, I didn't know if the `y` hotkey.
Happy that the patch worked :-)
