### ISSUE TITLE
ErrorException: Undefined index: mu on src/Xhgui/Profile.php:385

### ISSUE THREAD

**Issue by ngyuki** [perftools/xhgui#343]
Run xhgui with  `error_reporting=-1`.

```sh
php -S 0.0.0.0:80 -t webroot/ -d error_reporting=-1
```

Empty `profiler.flags` in php-profiler.

```php
$config = [
    'profiler.enable' => function () { return true; },
    'profiler.flags' => [],

    // ...snip...
];
$profiler = new \Xhgui\Profiler\Profiler($config);
$profiler->start();
```

Show profile results in xhgui, will see following error.

```
Slim Application Error

The application could not run because of the following error:

Details

Type: ErrorException
Code: 8
Message: Undefined index: mu
File: /xhgui/src/Xhgui/Profile.php
Line: 385

Trace

#0 /xhgui/src/Xhgui/Profile.php(385): Slim\Slim::handleErrors(8, 'Undefined index...', '/xhgui/src/Xhgu...', 385, Array)
#1 /xhgui/src/Xhgui/Controller/RunController.php(102): XHGui\Profile->calculateSelf()
#2 /xhgui/src/routes.php(41): XHGui\Controller\RunController->view()
#3 [internal function]: {closure}()
#4 /xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#6 /xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#9 /xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#10 /xhgui/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): XHGui\Middleware\RenderMiddleware->call()
#11 /xhgui/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#12 /xhgui/webroot/index.php(13): Slim\Slim->run()
#13 {main}
```

**Comment by glensc** [comment]
@ngyuki: which storage?

**Comment by glensc** [comment]
seems to be the same problem: https://github.com/perftools/xhgui/issues/146

**Comment by ngyuki** [comment]
@glensc Thank you for reply. I using mongodb.

**Comment by ngyuki** [comment]
> https://github.com/perftools/xhgui/issues/146#issuecomment-129961586
> Yes, xhgui assumes you have cpu profiling enabled throughout the code unfortunately.

If that is case, I think it would be more friendly if `ProfilingFlags::CPU` and `ProfilingFlags::MEMORY` could not be disabled.

**Comment by glensc** [comment]
Is the profiling even useful if you have not enabled any profiling flags?

I believe that just hiding the notices is not a solution.

**Comment by ngyuki** [comment]
I can only confirm it with tideways_xhprof, but even if all the flags are disabled, only the wall time is measured.

I think the problem is that the flag defaults to empty in php-profiler, so xhgui errors in that config.

https://github.com/perftools/php-profiler/blob/master/src/Profiler.php#L280

**Comment by glensc** [comment]
so, only wall time is measured is actually useful?

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by ngyuki** [comment]
It's same problem as #146, so I'll close it

**Comment by glensc** [comment]
I tested submitting only wall time, the output is useful. just cpu and mem columns are empty.
