### ISSUE TITLE
Undefined index: page

### ISSUE THREAD

**Issue by Mte90** [perftools/xhgui#369]
An user reported a bug with xhgui, https://github.com/perftools/xhgui/blob/e7d4d21a777a6580b115247782ce53bf5fac1517/src/Xhgui/Searcher/PdoSearcher.php#L101

From here https://github.com/perftools/xhgui/blob/master/src/Xhgui/Searcher/PdoSearcher.php#L101 it is not clear if that key exists.

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by Mte90** [comment]
Sorry I forgot it again

**Comment by glensc** [comment]
This PR covers this topic: https://github.com/perftools/xhgui/pull/363

but I have not able to test the branch other than making the CI pass.

**Comment by Mte90** [comment]
I don't see any error but in waterfall page there is this:
![Screenshot_2020-11-04 XHGui](https://user-images.githubusercontent.com/403283/98150691-59e25200-1ecf-11eb-876d-21b1d8ad7b6e.png)

**Comment by glensc** [comment]
> I don't see any error.

???

**Comment by Mte90** [comment]
Sorry I meant that I tested with that branch and I don't see any error.

**Comment by glensc** [comment]
You could have said that in that PR then, would be made more sense.

merging it then.
