### ISSUE TITLE
Empty xhgui list also if sqlite has content

### ISSUE THREAD

**Issue by Mte90** [perftools/xhgui#371]
Attached there is a sqlite database with some urls but xhgui doesn't show anything.

Those are the settings if they can help on understand the issue
```
$defaults = array(
    'debug' => true,
    'save.handler' => 'pdo',
    'pdo' => array(
        'dsn' => 'sqlite:/tmp/xhgui.sqlite3',
        'user' => null,
        'pass' => null,
        'table' => 'results'
    ),
    'templates.path' => dirname(__DIR__) . '/src/templates',
    'date.format' => 'M jS H:i:s',
    'detail.count' => 6,
    'page.limit' => 25,
    'run.view.filter.names' => array(
        'wp_*',
        'Composer*',
    ),
);
```

[xhgui.zip](https://github.com/perftools/xhgui/files/5512012/xhgui.zip)

**Comment by tquensen** [comment]
I have the same issue with mysql (MariaDB)

Data gets inserted successfully via importer but the GUI doesn't show anything


`cat config/config.php
<?php
return array(
        'save.handler' => 'pdo',
        'pdo' => [
                'dsn'    => 'mysql:host=localhost;dbname=xhgui',
                'user' => 'root',
                'pass' => '****',
                'table' => 'profiles'
        ],
        'upload.token' => '****'
);`
