### ISSUE TITLE
Can't auth with mongodb

### ISSUE THREAD

**Issue by athoune** [perftools/xhgui#420]
XHGui use https://github.com/alcaeus/mongo-php-adapter, and it says :
> The authenticate method is not supported. To connect to a database with authentication, please supply the credentials using the connection string.

In https://github.com/perftools/xhgui/blob/99d2d88f70d4a54f4a161dece9b106c3eb72e349/src/ServiceProvider/MongoStorageProvider.php#L46 the `MongoClient` is configured without username/password.

I set auth in `config.php` as suggested here https://github.com/perftools/xhgui/blob/99d2d88f70d4a54f4a161dece9b106c3eb72e349/config/config.default.php#L30 but this error happens `MongoDB\Driver\Exception\ServerException: command find requires authentication in /var/www/vendor/mongodb/mongodb/src/Operation/Find.php:280`

Is it possible to uses mongodb with a username/password ?

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by athoune** [comment]
ok, it's more readable with permalinks, sorry.

**Comment by athoune** [comment]
I can authenticate with an ugly hack in config.php :

```php
$mongo_hostname = getenv('XHGUI_MONGO_HOSTNAME') ?: '127.0.0.1';
$mongo_port = getenv('XHGUI_MONGO_PORT') ?: 27017;
$mongo_username = getenv('XHGUI_MONGO_USER') ?: 'xhprof';
$mongo_password = getenv('XHGUI_MONGO_PASSWORD') ?: 'pazzword';

return [
'db.host' => "mongodb://$mongo_username:$mongo_password@$mongo_hostname:$mongo_port",
// lots of config here
];

```

**Comment by glensc** [comment]
The point of permalinks is that links stay working if code is changed.

**Comment by glensc** [comment]
From this changeset:
- https://github.com/perftools/xhgui/pull/382

I read that password should go under 'options'. Did you try that?

you seem to be using old `db.host` syntax, you should use new syntax that the PR introduced, and is present as an example in config as well: `config/config.default.php`.

**Comment by athoune** [comment]
hum, I mess something with too many moving parts, mongodb image changed its behavior.
I didn't notice when user wasn't created in mongodb, and when I put username/password in the wrong place (outside 'options').

```php
'mongodb' => [
        'options' => [
            'username' => getenv('XHGUI_MONGO_USER') ?: 'xhprof',
            'password' => getenv('XHGUI_MONGO_PASSWORD') ?: 'pazzword',
        ],
]
```

It works.

Sorry for the noise.

**Comment by glensc** [comment]
@athoune please close the issue if problem solved!

**Comment by glensc** [comment]
@athoune what you think can the 'username'/'password' filled by default with `null` or `false`, or that will break setups where authentication is not enabled?

I was thinking, that maybe setup to `config/config.default.php`:

```php
'mongodb' => [
        'options' => [
            'username' => getenv('XHGUI_MONGO_USERNAME') ?: null,
            'password' => getenv('XHGUI_MONGO_PASSWORD') ?: null,
        ],
]
```

**Comment by glensc** [comment]
@athoune hallo?

**Comment by athoune** [comment]
Your patch is nice, thanks.

**Comment by glensc** [comment]
@athoune can you please answer the question I asked you?

**Comment by glensc** [comment]
@athoune?

**Comment by glensc** [comment]
@athoune where did you go?

please answer the question:
- https://github.com/perftools/xhgui/issues/420#issuecomment-820615673

**Comment by glensc** [comment]
Pity, when the user wants something, the developer needs to respond, but when the developer wants contribution back the user disappears.
