### ISSUE TITLE
Docker Hub images

### ISSUE THREAD

**Issue by ossinkine** [perftools/xhgui#427]
Hi there!

Looks like automated builds on Docker Hub don't work anymore and there is no the newest release there.
Please kindly add it and update images sometimes if possible.
Thank you!

**Comment by glensc** [comment]
Please be specific about what you think is missing and from where.

**Comment by ossinkine** [comment]
I'm talking about Docker Hub images of this project https://hub.docker.com/r/xhgui/xhgui/tags.
The latest tag is 0.18.1 is dated 8 months ago, 0.18.2 is not published.

**Comment by glensc** [comment]
There is no build automation

**Comment by ossinkine** [comment]
Please do it manually

**Comment by glensc** [comment]
The automation does not get fired:
- https://github.com/perftools/xhgui/pull/428#issuecomment-937574665
- https://github.com/perftools/xhgui/pull/431#issuecomment-948501244

any help to solve this is welcome.

**Comment by glensc** [comment]
Opened question in laminas support forums:
- https://discourse.laminas.dev/t/support-automatic-releases-cant-figure-why-tags-action-does-not-fire/2586

**Comment by glensc** [comment]
Re-post as an issue, as the forum has not received a reply:
- https://github.com/laminas/automatic-releases/issues/175

**Comment by ossinkine** [comment]
Since GitHub actions don't fire an event, I suggest would be better to create the issue in https://github.com/actions/runner not in https://github.com/laminas/automatic-releases.

Also try to use syntax as described here https://github.com/actions/runner/issues/1007 (on create with no tags filter).

**Comment by ossinkine** [comment]
Also try to use single quotes instead of double quotes, everywhere in documentation they are used, maybe it affects 🤷‍♂️ 
```yaml
on:
  push:
    tags:
      - '*.*.*'
```

**Comment by glensc** [comment]
1. changing to on create had no effect as I already guessed: https://github.com/laminas/automatic-releases/issues/175#issuecomment-1014662213
2. yaml syntax doesn't matter

**Comment by ossinkine** [comment]
1. You added `on create` but you also specified tags filter. Did you try with no tags filter? Looks like this is not supported.
2. Did you check this or just guessing?

**Comment by glensc** [comment]
1. looks like not supported -> reference to your claim?
2. I'm not guessing. I know YAML.

I'm not interested in wasting my time on random guesses, I did that, and it lead to nowhere but lots of my time and nerves lost.

if you want to play with all that, you can do all of that release flow in your own fork.  if you come up with a solution then I can adapt it here.

**Comment by glensc** [comment]
Also, another symptom that this is about events not fired by likely actions to actions event loop block:
- https://github.com/laminas/automatic-releases/issues/175#issuecomment-1013881532

**Comment by glensc** [comment]
Merge up problem solved too:
- https://github.com/laminas/automatic-releases/issues/175#issuecomment-1051025855

closing
