### ISSUE TITLE
flush() can cause a warning when output buffering is enabled

### ISSUE THREAD

**Issue by preinheimer** [perftools/xhgui#44]
In a script I see:
        header('X-Bar: foo');
    ob_start("ob_gzhandler");
    echo $json;
    exit;
With XHGui on I get `[Tue Aug 13 15:01:50 2013] [error] [client 192.168.3.1] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0`

If I comment out the `flush()` line this goes away. Need to diagnose further.

**Comment by glensc** [comment]
the flush can be turned off in php-profiler:
- https://github.com/perftools/php-profiler/pull/25

another solution is to enable `output_buffering = on`
