### ISSUE TITLE
Missing required parameter in RunController:274

### ISSUE THREAD

**Issue by ddanev-yotpo** [perftools/xhgui#471]
When trying to compare runs the following error comes up.

```
"Message: Too few arguments to function XHGui\RequestProxy::get(), 0 passed in /var/www/xhgui/src/Controller/RunController.php on line 274 and at least 1 expected"
```
https://github.com/perftools/xhgui/blob/448c6d722440171612f9a257dcd6912fc940aae8/src/Controller/RunController.php#L274

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by glensc** [comment]
pull request is welcome!

**Comment by glensc** [comment]
Fixed by https://github.com/perftools/xhgui/pull/481
