### ISSUE TITLE
Allow filtering based on HTTP_HOST

### ISSUE THREAD

**Issue by preinheimer** [perftools/xhgui#63]
May require a meta-table to avoid a horrendous cost (to get the distinct list), but it would be nice to be able to filter results based on the HTTP_HOST when multiple domains push to the same server.

**Comment by koekaverna** [comment]
@glensc 
I added `server-name` filter, and changed links and search forms. Please take a look.
https://github.com/perftools/xhgui/pull/425
It's messy in case I don't clear about where to use `url` and `simple_url`, so I leave this as it was

**Comment by glensc** [comment]
https://github.com/perftools/xhgui/pull/425 is merged
