### ISSUE TITLE
Composer Requirements

### ISSUE THREAD

**Issue by kuncajs** [perftools/xhgui#85]
Hello developers,
as even your installation guide says you can use xhgui even when you do not have access to mongoDB directly. This is exactly our case - we do not want to run mongo on our production just for profiling, instead of it we would like to generate files, download them periodically and analyze locally, however we will not be able to compose this project as dependency in composer on production because this project has ext-mongo as a requirement.

It is not a requirement though as you CAN run without it and you even suggest it in the manual. Do you think it would be wise to remove this dependency? Otherwise I will need to fork :-) Thank you!

PS I forgot to show some appreciation. The project is very nice, GUI working, callgraph interactive (!) and everything works. This XHProf GUI is much better than the other ones I tried. Thanks, guys!

**Comment by pavelsmolka** [comment]
Hi,

It was possible to install `xhgui` as a dependency without having `ext-mongo` installed for quite a long time. However, in commit `c3a3f43`, a new dependency has been added:

https://github.com/perftools/xhgui/commit/c3a3f43bf41a0a054152902c9bcdd41bc05b1bb7#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R17

I am not sure what the reason for adding the dependency was. I can't see anything from the commit itself. It'd be great if we can maintain `xhgui` as a data-capture tool, as suggested earlier in this thread, and separate the data-display logic. I guess I am not the only guy who wants to run xhgui-based profiling on the production machines, while not having `ext-mongo` installed there.

**Comment by markstory** [comment]
@pavelsmolka I can move that dependency into suggest. Splitting xhgui up might be an option in the future. I don't have a ton of time to do that right now though.

**Comment by pavelsmolka** [comment]
Hi, I have created a pull request, with simply moving the Mongo dependency to suggest. I have briefly checked the code, and I'm not sure whether some more changes need to be introduced for this MR to be accepted. I'm happy to put a bit more work into this, if you guide me into the right direction.

**Comment by lauripiisang** [comment]
Digging up graves, but FWIW, as @kuncajs proposed, I have extracted the minimal amount of code needed to provide a `data collector` from XHGUI project. 
This is version-agnostic, should work on PHP 5.3 - 7.1 and doesn't modify (aside from deleting) the original code.

see https://github.com/lauripiisang/xhgui-data-collector
There's a version up on packagist as well. 

Got scrutinizer rank up to 10.0 :)

**Comment by markstory** [comment]
@lauripiisang Would you be interested in moving that repository to this org? You could continue to maintain the collector, and we could work together to slim down this project to not contain the collector code.

**Comment by lauripiisang** [comment]
@markstory I don't see why not. the current project is just a very basic teardown of the unnecessaries with compatibility in mind, but I'd love for it to evolve into something more.

How do we go about doing that? 

P.S. on a different topic - please create tagged releases of `xhgui` project on packagist!

**Comment by markstory** [comment]
> P.S. on a different topic - please create tagged releases of xhgui project on packagist!

There has been a recent change to remove the version key in the composer.json that should fix tags not getting picked up going forward. There doesn't seem to be a way to backfill existing tags into packagist though.

**Comment by lauripiisang** [comment]
Clicking "update" in the project view should refresh all references

**Comment by markstory** [comment]
It doesn't. I pushed that button a few times last night :cry:. Could packagist not be finding the tags because the old tags are prefixed with `v`?

**Comment by glensc** [comment]
packagist tag problem solved: https://github.com/perftools/xhgui/pull/199#issuecomment-291960753

**Comment by lauripiisang** [comment]
I've pushed lauripiisang/xhgui-data-collector to perftools/xhgui-collector, but there are some issues to resolve:
https://github.com/perftools/xhgui-collector/issues/1

**Comment by Krinkle** [comment]
It looks like perftools/xhgui should at least depend on perftools/xhgui-collector. Rather than the code being duplicated. This would also keep perftools/xhgui backwards compatible with existing usage. The main concern is that the collector used in production is minimal.

**Comment by glensc** [comment]
common parts should be moved to separate library instead. this was also @lauripiisang opinion.

but this is likely not worked on (beside lack of time/interest/profit) because it would be major breakage for people who do not use composer for xhgui installation. currently it's standalone, no external (composer) dependencies.

this could be solved two ways:
- introduce major version, which requires composer
- upload tarballs to releases which contain dependencies (result of `composer install --no-dev`)

**Comment by markstory** [comment]
I think requiring composer might be an option now. Back when this project started, I don't think composer was as widely used as it is today. Making tarballs for releases isn't that hard either. I have some make scripts to do just that from automating releases in CakePHP.

**Comment by lauripiisang** [comment]
We could have some plans for major version then in general, like PSR-4 compatibility and perhaps some restructuring, better error handling.

WDYT?

**Comment by markstory** [comment]
> We could have some plans for major version then in general, like PSR-4 compatibility and perhaps some restructuring, better error handling.
> Perhaps we should consolidate these under an issue.

Sounds like a plan. I think there are a bunch of things we can and should improve.

**Comment by glensc** [comment]
[perftools/xhgui-collector] has been created, which is now superseded by [perftools/php-profiler] package.

[perftools/xhgui-collector]: https://github.com/perftools/xhgui-collector
[perftools/php-profiler]: https://github.com/perftools/php-profiler
